services:
  app-dev:
    container_name: next-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    working_dir: /app
    command: npm run dev
    profiles:
      - develop

  app-prd:
    container_name: next-prd
    build:
      context: .
      dockerfile: Dockerfile
      target: prd
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    profiles:
      - production
