// 生成した zod スキーマから、検証を伴わない定数だけを抜き出す。

/** 抜き出した定数 1 件。 */
export type ContractLimit = {
  /** 生成器が付けた名前。そのまま引き継ぐ。 */
  readonly name: string;
  /** `= ` の右辺。数値・文字列・正規表現のいずれかの literal。 */
  readonly literal: string;
};

/**
 * 1 行で閉じる `export const` の宣言。
 *
 * @remarks
 * 複数行にわたる宣言（スキーマの組み立て）は、1 行目が `;` で閉じないため当たりません。
 */
const DECLARATION = /^export const ([A-Za-z0-9_]+) = (.+);$/gm;

/**
 * 右辺が zod を参照しているか。
 *
 * @remarks
 * **受ける形を列挙しません。** 生成器は制約を数値・文字列・テンプレート literal・`new RegExp(...)`
 * と様々な形で出し、文字列の中に括弧が入ることもあります。列挙で受けると、生成器が形を変えるたびに
 * 定数が黙って落ちます。落としたい条件はただ 1 つ **「zod を引くかどうか」** —— 引く宣言を写すと、
 * この module 自身が zod を引くことになり、切り出した意味が消えます。
 */
const USES_ZOD = /\bzod\b/;

export function collectContractLimits(source: string): ContractLimit[] {
  return [...source.matchAll(DECLARATION)]
    .filter(([, , literal]) => !USES_ZOD.test(literal))
    .map(([, name, literal]) => ({ name, literal }));
}

/** 生成元のヘッダから契約の版を取り出す。突合（`make gen-api-check`）が読む行。 */
const SPEC_VERSION = /OpenAPI spec version:\s*(\S+)/;

/**
 * 定数だけを持つ module を組み立てる。
 *
 * @param generated - 生成された zod スキーマの中身。契約の版を読むために渡す。
 * @param limits - 抜き出した定数。
 *
 * @remarks
 * **版を書き写します。** 契約と生成物の版の突合は生成物のディレクトリ全体を見るため、版を持たない
 * ファイルが 1 つでもあると「生成器が版を書かなくなった」として落ちます。
 *
 * 出所は orval ではなくこの手順だと名乗ります。orval のヘッダをそのまま写すと、再生成しても
 * 現れないファイルが orval の出力を名乗ることになります。
 */
export function renderContractLimits(generated: string, limits: readonly ContractLimit[]): string {
  const version = SPEC_VERSION.exec(generated)?.[1] ?? "unknown";

  return [
    "/**",
    " * Generated by scripts/openapi/extract-limits.ts",
    " * Do not edit manually.",
    " *",
    " * 生成した zod スキーマから、検証を伴わない定数だけを写したもの。client はこちらを引く。",
    " *",
    ` * OpenAPI spec version: ${version}`,
    " */",
    "",
    ...limits.flatMap((limit) => [`export const ${limit.name} = ${limit.literal};`, ""]),
  ]
    .join("\n")
    .trimEnd()
    .concat("\n");
}
