// 生成した zod スキーマから、検証を伴わない定数だけを抜き出す。

/** 抜き出した定数 1 件。 */
export type ContractLimit = {
  /** 生成器が付けた名前。そのまま引き継ぐ。 */
  readonly name: string;
  /** `= ` の右辺。数値・文字列・正規表現のいずれかの literal。 */
  readonly literal: string;
};

/**
 * 宣言の始まり。ここで区切ってから 1 件ずつ読む。
 *
 * @remarks
 * **正規表現ひとつで 1 件を取り切ろうとしません。** 生成器の生の出力ではスキーマが `})` で終わり
 * `;` を持たず（`;` は整形が付ける）、行末の `;` までを最短で取ると、次の宣言までを飲み込んで
 * 内側の定数が消えます。整形の前に走るか後に走るかで結果が変わる形を持ち込まないため、
 * **宣言の始まりで区切ってから**、その中だけを見ます。
 */
const DECLARATION_START = /^export const (?=\w+ = )/m;

/** 宣言の終わり。行末の `;`。 */
const DECLARATION_END = /;\s*$/m;

/**
 * 右辺が zod を参照しているか。
 *
 * @remarks
 * **受ける形を列挙しません。** 生成器は制約を数値・文字列・テンプレート literal・`new RegExp(...)`
 * と様々な形で出し、文字列の中に括弧が入ることもあります。列挙で受けると、生成器が形を変えるたびに
 * 定数が黙って落ちます。落としたい条件はただ 1 つ **「zod を引くかどうか」** —— 引く宣言を写すと、
 * この module 自身が zod を引くことになり、切り出した意味が消えます。
 */
const USES_ZOD = /\bzod\b/;

/**
 * @param source - 生成器の**整形前の生の出力**。`make gen-api` は orval のあとに `pnpm fix` を
 *   掛けるが、この抜き出しはその前に走る（`extract-limits.ts`）。
 * @returns 宣言された順のまま。zod を引く宣言は落とす。
 */
export function collectContractLimits(source: string): ContractLimit[] {
  return source
    .split(DECLARATION_START)
    .slice(1)
    .flatMap((declaration) => {
      const separator = declaration.indexOf(" = ");
      const end = declaration.search(DECLARATION_END);

      if (separator < 0 || end < 0) {
        return [];
      }

      const name = declaration.slice(0, separator);
      const literal = declaration.slice(separator + 3, end).replace(/[ \t]*\n[ \t]*/g, "");

      return USES_ZOD.test(literal) ? [] : [{ name, literal }];
    });
}

/** 生成元のヘッダから契約の版を取り出す。突合（`make gen-api-check`）が読む行。 */
const SPEC_VERSION = /OpenAPI spec version:\s*(\S+)/;

/**
 * 定数だけを持つ module を組み立てる。
 *
 * @param generated - 生成された zod スキーマの中身。契約の版を読むために渡す。
 * @param limits - 抜き出した定数。
 *
 * @remarks
 * **版を書き写します。** 契約と生成物の版の突合は生成物のディレクトリ全体を見るため、版を持たない
 * ファイルが 1 つでもあると「生成器が版を書かなくなった」として落ちます。
 *
 * 出所は orval ではなくこの手順だと名乗ります。orval のヘッダをそのまま写すと、再生成しても
 * 現れないファイルが orval の出力を名乗ることになります。
 *
 * **定数が 1 つも無ければ組み立てません。** 契約によっては上限も書式も持たず、書き出すとヘッダ
 * だけのファイルが残ります。「定数だけを写したもの」と名乗って中身が空のファイルは、読む人に
 * 「抽出が壊れているのか、契約に無いのか」を判じさせます。存在するファイルは必ず中身を持つ側へ倒す。
 *
 * @returns 定数が無ければ null
 */
export function renderContractLimits(
  generated: string,
  limits: readonly ContractLimit[],
): string | null {
  if (limits.length === 0) {
    return null;
  }

  const version = SPEC_VERSION.exec(generated)?.[1] ?? "unknown";

  return [
    "/**",
    " * Generated by scripts/openapi/extract-limits.ts",
    " * Do not edit manually.",
    " *",
    " * 生成した zod スキーマから、検証を伴わない定数だけを写したもの。client はこちらを引く。",
    " *",
    ` * OpenAPI spec version: ${version}`,
    " */",
    "",
    ...limits.flatMap((limit) => [`export const ${limit.name} = ${limit.literal};`, ""]),
  ]
    .join("\n")
    .trimEnd()
    .concat("\n");
}
