import { describe, expect, it } from "vitest";
import { extractSpecVersion, findStampDrift, stampedArtifactPaths } from "./generated-stamp";
import type { OpenApiSource } from "./sources-manifest";

const source: OpenApiSource = {
  name: "api",
  repo: "Tomy-ch/go-boilerplate",
  path: "openapi/openapi.gen.yaml",
  ref: "130b179afd0146ce393626064ca2facaefa059f8",
  sha: "aa62bff3e087b544494f012d5009702492e40d79",
  fetchedAt: "2026-08-07T00:00:00.000Z",
};

function artifact(version: string) {
  return [
    {
      path: "src/adapters/gen/api/endpoints.zod.ts",
      content: `/**\n * Generated by orval\n * OpenAPI spec version: ${version}\n */\n`,
    },
  ];
}

describe("正常系", () => {
  describe("stampedArtifactPaths", () => {
    it("契約名から突合対象の生成物を決める", () => {
      expect(stampedArtifactPaths("api")).toEqual(["src/adapters/gen/api/endpoints.zod.ts"]);
    });
  });
  describe("extractSpecVersion", () => {
    it("生成物のヘッダから契約の版を取り出す", () => {
      expect(extractSpecVersion(" * OpenAPI spec version: 2.2.0+aa62bff\n")).toBe("2.2.0+aa62bff");
    });
  });
  describe("findStampDrift", () => {
    it("版が一致していればずれを報告しない", () => {
      expect(findStampDrift([source], artifact("2.2.0+aa62bff"))).toEqual([]);
    });
  });
});

describe("異常系", () => {
  describe("extractSpecVersion", () => {
    it("版を持たない生成物を null にする", () => {
      expect(extractSpecVersion("/** Generated by orval */\n")).toBeNull();
    });
  });
  describe("findStampDrift", () => {
    it("契約が未取得なら生成前に落とす", () => {
      expect(findStampDrift([{ ...source, sha: null }], artifact("2.2.0+aa62bff"))).toEqual([
        "openapi/api.gen.yaml: 契約が未取得です",
      ]);
    });
    it("生成物が無いことを報告する", () => {
      expect(findStampDrift([source], [])).toEqual([
        "src/adapters/gen/api/endpoints.zod.ts: 生成物がありません",
      ]);
    });
    it("版を持たない生成物を報告する", () => {
      expect(
        findStampDrift(
          [source],
          [{ path: "src/adapters/gen/api/endpoints.zod.ts", content: "/** orval */\n" }],
        ),
      ).toEqual(["src/adapters/gen/api/endpoints.zod.ts: 生成物が契約の版を持っていません"]);
    });
    it("契約を取得したのに生成していない状態を報告する", () => {
      expect(findStampDrift([source], artifact("2.2.0+0000000"))).toEqual([
        "src/adapters/gen/api/endpoints.zod.ts: 契約は +aa62bff ですが生成物は 2.2.0+0000000 です",
      ]);
    });
  });
});
