import { describe, expect, it } from "vitest";
import { contractArtifactRoots, extractSpecVersion, findStampDrift } from "./generated-stamp";
import type { OpenApiSource } from "./sources-manifest";

const source: OpenApiSource = {
  name: "api",
  repo: "Tomy-ch/go-boilerplate",
  path: "openapi/openapi.gen.yaml",
  ref: "130b179afd0146ce393626064ca2facaefa059f8",
  sha: "aa62bff3e087b544494f012d5009702492e40d79",
  fetchedAt: "2026-08-07T00:00:00.000Z",
};

function artifact(path: string, version: string | null) {
  const header = version === null ? "" : `\n * OpenAPI spec version: ${version}`;

  return { path, content: `/**\n * Generated by orval${header}\n */\n` };
}

describe("正常系", () => {
  describe("contractArtifactRoots", () => {
    it("契約名から生成物のディレクトリを決める", () => {
      expect(contractArtifactRoots("api")).toEqual(["src/adapters/gen/api", "mocks/api"]);
    });
  });
  describe("extractSpecVersion", () => {
    it("生成物のヘッダから契約の版を取り出す", () => {
      expect(extractSpecVersion(" * OpenAPI spec version: 2.2.0+aa62bff\n")).toBe("2.2.0+aa62bff");
    });
  });
  describe("findStampDrift", () => {
    it("版が一致していればずれを報告しない", () => {
      const artifacts = [
        artifact("src/adapters/gen/api/endpoints.zod.ts", "2.2.0+aa62bff"),
        artifact("src/adapters/gen/api/model/productResponse.ts", "2.2.0+aa62bff"),
        artifact("mocks/api/endpoints.msw.ts", "2.2.0+aa62bff"),
      ];

      expect(findStampDrift([source], artifacts)).toEqual([]);
    });
    it("他の契約の生成物を突合の対象にしない", () => {
      const artifacts = [
        artifact("src/adapters/gen/api/endpoints.zod.ts", "2.2.0+aa62bff"),
        artifact("src/adapters/gen/auth/endpoints.zod.ts", "1.0.0+9be739a"),
      ];

      expect(findStampDrift([source], artifacts)).toEqual([]);
    });
  });
});

describe("異常系", () => {
  describe("extractSpecVersion", () => {
    it("版を持たない生成物を null にする", () => {
      expect(extractSpecVersion("/** Generated by orval */\n")).toBeNull();
    });
  });
  describe("findStampDrift", () => {
    it("契約が未取得なら生成前に落とす", () => {
      const artifacts = [artifact("src/adapters/gen/api/endpoints.zod.ts", "2.2.0+aa62bff")];

      expect(findStampDrift([{ ...source, sha: null }], artifacts)).toEqual([
        "api: 契約が未取得です",
      ]);
    });
    it("生成物が 1 件も無いことを報告する", () => {
      expect(findStampDrift([source], [])).toEqual(["api: 生成物がありません"]);
    });
    it("版を持たない生成物を報告する", () => {
      const artifacts = [artifact("src/adapters/gen/api/endpoints.zod.ts", null)];

      expect(findStampDrift([source], artifacts)).toEqual([
        "api: 契約は +aa62bff ですが 1 件が版を持ちません（例: src/adapters/gen/api/endpoints.zod.ts）",
      ]);
    });
    it("契約を取得したのに生成していない状態を報告する", () => {
      const artifacts = [artifact("src/adapters/gen/api/endpoints.zod.ts", "2.2.0+0000000")];

      expect(findStampDrift([source], artifacts)).toEqual([
        "api: 契約は +aa62bff ですが 1 件が版 2.2.0+0000000 です（例: src/adapters/gen/api/endpoints.zod.ts）",
      ]);
    });
    it("mocks 側だけが古い状態を報告する", () => {
      const artifacts = [
        artifact("src/adapters/gen/api/endpoints.zod.ts", "2.2.0+aa62bff"),
        artifact("mocks/api/endpoints.msw.ts", "2.2.0+0000000"),
      ];

      expect(findStampDrift([source], artifacts)).toEqual([
        "api: 契約は +aa62bff ですが 1 件が版 2.2.0+0000000 です（例: mocks/api/endpoints.msw.ts）",
      ]);
    });
    it("ずれた生成物を版ごとにまとめる", () => {
      const artifacts = [
        artifact("src/adapters/gen/api/model/a.ts", "2.2.0+0000000"),
        artifact("src/adapters/gen/api/model/b.ts", "2.2.0+0000000"),
      ];

      expect(findStampDrift([source], artifacts)).toEqual([
        "api: 契約は +aa62bff ですが 2 件が版 2.2.0+0000000 です（例: src/adapters/gen/api/model/a.ts）",
      ]);
    });
  });
});
