/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Mock Auth Server (OIDC Provider)
 * ローカル開発用の疑似 OIDC Provider。Authorization Code Flow + PKCE(S256) を最小構成で提供する。
 *
 * 本サービスは go-boilerplate 本体とは別サービスであり、OpenAPI をこのディレクトリ配下にローカルで持つ
 * （主 API 契約 `openapi/` は汚さない）。エンドポイントは 3 系統に分かれる:
 *
 * - `/oidc/*` — OAuth2 / OIDC 標準エンドポイント（authorize / token / userinfo / logout）。
 * - `/bypass/*` — テスト用ショートカット（固定 Profile での token / session 発行）。dev-gate 限定。
 * - `/admin/*` — 運用補助（fixture reset / users 一覧 / key rotate スタブ）。dev-gate 限定。
 *
 * パラメータ・フィールドは OAuth2(RFC 6749) / PKCE(RFC 7636) / RFC 9068 / OIDC Core に従い snake_case。
 *
 * OpenAPI spec version: 1.0.0+9be739a
 */
import type {
  AdminReset200,
  AdminUsersResponse,
  BypassSession200,
  BypassSessionBody,
  BypassTokenBody,
  Jwks,
  KeyRotationRequest,
  KeyState,
  OAuthError,
  OidcAuthorizeParams,
  OidcConfiguration,
  OidcLogout200,
  OidcLogoutBody,
  OidcTokenBody,
  TokenResponse,
  UserInfo,
} from "../../src/adapters/gen/auth/model";

export type getOpenidConfigurationResponse200 = {
  data: OidcConfiguration;
  status: 200;
};

export type getOpenidConfigurationResponseSuccess = getOpenidConfigurationResponse200 & {
  headers: Headers;
};

export type getOpenidConfigurationResponse = getOpenidConfigurationResponseSuccess;

export const getGetOpenidConfigurationUrl = () => {
  return `/.well-known/openid-configuration`;
};

/**
 * @summary OIDC Discovery 文書の取得
 */
export const getOpenidConfiguration = async (
  options?: RequestInit,
): Promise<getOpenidConfigurationResponse> => {
  const res = await fetch(getGetOpenidConfigurationUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOpenidConfigurationResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getOpenidConfigurationResponse;
};

export type getJwksResponse200 = {
  data: Jwks;
  status: 200;
};

export type getJwksResponseSuccess = getJwksResponse200 & {
  headers: Headers;
};

export type getJwksResponse = getJwksResponseSuccess;

export const getGetJwksUrl = () => {
  return `/.well-known/jwks.json`;
};

/**
 * @summary JWK Set の取得
 */
export const getJwks = async (options?: RequestInit): Promise<getJwksResponse> => {
  const res = await fetch(getGetJwksUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getJwksResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getJwksResponse;
};

export type oidcAuthorizeResponse302 = {
  data: void;
  status: 302;
};

export type oidcAuthorizeResponse400 = {
  data: OAuthError;
  status: 400;
};
export type oidcAuthorizeResponseError = (oidcAuthorizeResponse302 | oidcAuthorizeResponse400) & {
  headers: Headers;
};

export type oidcAuthorizeResponse = oidcAuthorizeResponseError;

export const getOidcAuthorizeUrl = (params: OidcAuthorizeParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oidc/authorize?${stringifiedParams}` : `/oidc/authorize`;
};

/**
 * client_id / redirect_uri を完全一致で検証する。両者が不正でリダイレクト不能な場合のみ 400（JSON）、 それ以外の不正は redirect_uri へ 302 の error redirect（state を反映）で返す。成功時は code を付与して 302。
 * @summary 認可リクエスト（Authorization Code Flow + PKCE S256）
 */
export const oidcAuthorize = async (
  params: OidcAuthorizeParams,
  options?: RequestInit,
): Promise<oidcAuthorizeResponse> => {
  const res = await fetch(getOidcAuthorizeUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: oidcAuthorizeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as oidcAuthorizeResponse;
};

export type oidcTokenResponse200 = {
  data: TokenResponse;
  status: 200;
};

export type oidcTokenResponse400 = {
  data: OAuthError;
  status: 400;
};

export type oidcTokenResponseSuccess = oidcTokenResponse200 & {
  headers: Headers;
};
export type oidcTokenResponseError = oidcTokenResponse400 & {
  headers: Headers;
};

export type oidcTokenResponse = oidcTokenResponseSuccess | oidcTokenResponseError;

export const getOidcTokenUrl = () => {
  return `/oidc/token`;
};

/**
 * form-urlencoded で受け取り、code の単回 consume・PKCE(S256) code_verifier 検証・redirect_uri 完全一致を行う。 成功時に access_token + id_token を発行する。public client のため client 認証は none。
 * @summary トークンエンドポイント（authorization_code + PKCE 検証）
 */
export const oidcToken = async (
  oidcTokenBody: OidcTokenBody,
  options?: RequestInit,
): Promise<oidcTokenResponse> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`grant_type`, oidcTokenBody.grant_type);
  formUrlEncoded.append(`code`, oidcTokenBody.code);
  formUrlEncoded.append(`redirect_uri`, oidcTokenBody.redirect_uri);
  formUrlEncoded.append(`client_id`, oidcTokenBody.client_id);
  formUrlEncoded.append(`code_verifier`, oidcTokenBody.code_verifier);

  const res = await fetch(getOidcTokenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded", ...options?.headers },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: oidcTokenResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as oidcTokenResponse;
};

export type oidcUserinfoResponse200 = {
  data: UserInfo;
  status: 200;
};

export type oidcUserinfoResponse401 = {
  data: OAuthError;
  status: 401;
};

export type oidcUserinfoResponseSuccess = oidcUserinfoResponse200 & {
  headers: Headers;
};
export type oidcUserinfoResponseError = oidcUserinfoResponse401 & {
  headers: Headers;
};

export type oidcUserinfoResponse = oidcUserinfoResponseSuccess | oidcUserinfoResponseError;

export const getOidcUserinfoUrl = () => {
  return `/oidc/userinfo`;
};

/**
 * Bearer access token を必須とし、対応する subject の claim を whitelist で返す。 ID Token（typ != at+jwt）は拒否する。
 * @summary UserInfo エンドポイント
 */
export const oidcUserinfo = async (options?: RequestInit): Promise<oidcUserinfoResponse> => {
  const res = await fetch(getOidcUserinfoUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: oidcUserinfoResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as oidcUserinfoResponse;
};

export type oidcLogoutResponse200 = {
  data: OidcLogout200;
  status: 200;
};

export type oidcLogoutResponse302 = {
  data: void;
  status: 302;
};

export type oidcLogoutResponse400 = {
  data: OAuthError;
  status: 400;
};

export type oidcLogoutResponseSuccess = oidcLogoutResponse200 & {
  headers: Headers;
};
export type oidcLogoutResponseError = (oidcLogoutResponse302 | oidcLogoutResponse400) & {
  headers: Headers;
};

export type oidcLogoutResponse = oidcLogoutResponseSuccess | oidcLogoutResponseError;

export const getOidcLogoutUrl = () => {
  return `/oidc/logout`;
};

/**
 * session を破棄し、post_logout_redirect_uri が登録済みなら 302 で戻す（state 反映）。 未登録の redirect や不正時は 400。
 * @summary ログアウト（RP-Initiated Logout）
 */
export const oidcLogout = async (
  oidcLogoutBody?: OidcLogoutBody,
  options?: RequestInit,
): Promise<oidcLogoutResponse> => {
  const formUrlEncoded = new URLSearchParams();
  if (oidcLogoutBody?.id_token_hint !== undefined) {
    formUrlEncoded.append(`id_token_hint`, oidcLogoutBody.id_token_hint);
  }
  if (oidcLogoutBody?.post_logout_redirect_uri !== undefined) {
    formUrlEncoded.append(`post_logout_redirect_uri`, oidcLogoutBody.post_logout_redirect_uri);
  }
  if (oidcLogoutBody?.state !== undefined) {
    formUrlEncoded.append(`state`, oidcLogoutBody.state);
  }

  const res = await fetch(getOidcLogoutUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded", ...options?.headers },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: oidcLogoutResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as oidcLogoutResponse;
};

export type bypassTokenResponse200 = {
  data: TokenResponse;
  status: 200;
};

export type bypassTokenResponse400 = {
  data: OAuthError;
  status: 400;
};

export type bypassTokenResponseSuccess = bypassTokenResponse200 & {
  headers: Headers;
};
export type bypassTokenResponseError = bypassTokenResponse400 & {
  headers: Headers;
};

export type bypassTokenResponse = bypassTokenResponseSuccess | bypassTokenResponseError;

export const getBypassTokenUrl = () => {
  return `/bypass/token`;
};

/**
 * Authorization Code Flow を経ずに、subject と固定 Profile から access token を直接発行する。 異常系 Profile（expired / wrong-issuer 等）で Go 側検証を試験する。dev-gate 限定。旧 POST /test/token の移行先。
 * @summary 固定 Profile での access token 発行（テスト用）
 */
export const bypassToken = async (
  bypassTokenBody?: BypassTokenBody,
  options?: RequestInit,
): Promise<bypassTokenResponse> => {
  const res = await fetch(getBypassTokenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(bypassTokenBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bypassTokenResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bypassTokenResponse;
};

export type bypassSessionResponse200 = {
  data: BypassSession200;
  status: 200;
};

export type bypassSessionResponse400 = {
  data: OAuthError;
  status: 400;
};

export type bypassSessionResponseSuccess = bypassSessionResponse200 & {
  headers: Headers;
};
export type bypassSessionResponseError = bypassSessionResponse400 & {
  headers: Headers;
};

export type bypassSessionResponse = bypassSessionResponseSuccess | bypassSessionResponseError;

export const getBypassSessionUrl = () => {
  return `/bypass/session`;
};

/**
 * authorize の UI を経ずに、subject に対するログイン済み session を直接作成する。 logout / RP-Initiated Logout の試験に使う。dev-gate 限定。
 * @summary 疑似ログインセッションの直接発行（テスト用）
 */
export const bypassSession = async (
  bypassSessionBody?: BypassSessionBody,
  options?: RequestInit,
): Promise<bypassSessionResponse> => {
  const res = await fetch(getBypassSessionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(bypassSessionBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bypassSessionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bypassSessionResponse;
};

export type adminListUsersResponse200 = {
  data: AdminUsersResponse;
  status: 200;
};

export type adminListUsersResponseSuccess = adminListUsersResponse200 & {
  headers: Headers;
};

export type adminListUsersResponse = adminListUsersResponseSuccess;

export const getAdminListUsersUrl = () => {
  return `/admin/users`;
};

/**
 * 登録済みの疑似ユーザー一覧を返す。dev-gate 限定。旧 GET /test/users の移行先。
 * @summary 固定 User Fixture の一覧取得
 */
export const adminListUsers = async (options?: RequestInit): Promise<adminListUsersResponse> => {
  const res = await fetch(getAdminListUsersUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminListUsersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as adminListUsersResponse;
};

export type adminResetResponse200 = {
  data: AdminReset200;
  status: 200;
};

export type adminResetResponseSuccess = adminResetResponse200 & {
  headers: Headers;
};

export type adminResetResponse = adminResetResponseSuccess;

export const getAdminResetUrl = () => {
  return `/admin/reset`;
};

/**
 * 発行済み code / session の揮発ストアを初期化する。fixture（users / clients）はプロセス再起動で初期化され、本エンドポイントでは再読込しない。dev-gate 限定。
 * @summary 揮発ストアのリセット
 */
export const adminReset = async (options?: RequestInit): Promise<adminResetResponse> => {
  const res = await fetch(getAdminResetUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminResetResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as adminResetResponse;
};

export type adminRotateKeysResponse200 = {
  data: KeyState;
  status: 200;
};

export type adminRotateKeysResponse400 = {
  data: OAuthError;
  status: 400;
};

export type adminRotateKeysResponseSuccess = adminRotateKeysResponse200 & {
  headers: Headers;
};
export type adminRotateKeysResponseError = adminRotateKeysResponse400 & {
  headers: Headers;
};

export type adminRotateKeysResponse = adminRotateKeysResponseSuccess | adminRotateKeysResponseError;

export const getAdminRotateKeysUrl = () => {
  return `/admin/keys/rotate`;
};

/**
 * 宣言的操作（add-key / promote / retire）で provider の署名鍵状態を遷移する。 JWKS の公開集合と現署名鍵を分離管理し、新旧 Token の並行検証・旧鍵退役を再現する。 Phase1 への復帰は POST /admin/reset。dev-gate 限定。
 * @summary 署名鍵ローテーション
 */
export const adminRotateKeys = async (
  keyRotationRequest: KeyRotationRequest,
  options?: RequestInit,
): Promise<adminRotateKeysResponse> => {
  const res = await fetch(getAdminRotateKeysUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(keyRotationRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminRotateKeysResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as adminRotateKeysResponse;
};
