/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Go Boilerplate API
 * This API is built on a modular, layered architecture using Go, Echo, and PostgreSQL.
 * It follows the Onion Architecture and is designed to be testable, maintainable, and scalable.
 *
 * The project is structured around domain-driven principles, with clean separation between interfaces,
 * use cases, domain entities, and infrastructure. All handlers are generated from the OpenAPI specification
 * using oapi-codegen, and strict typing is enforced across the system.
 *
 * This API is intended as a production-ready boilerplate that balances performance,
 * flexibility, and developer experience.
 *
 * OpenAPI spec version: 2.2.0+aa62bff
 */
import type {
  AddressCandidatesResponse,
  BadRequest400Response,
  Conflict409Response,
  DashboardSummaryResponse,
  ExchangeRateResponse,
  Forbidden403Response,
  GetAddressesParams,
  GetDashboardSummaryParams,
  GetExchangeRatesParams,
  GetProductsLowStockParams,
  GetProductsParams,
  GetProductsRankingParams,
  GetPurchasesParams,
  GetPurchasesShippableParams,
  GetUsersFeedParams,
  GetUsersParams,
  GetUsersSearchParams,
  InternalServerError500Response,
  MethodNotAllowed405Response,
  NotFound404Response,
  PayloadTooLarge413Response,
  PostPurchasesParams,
  PrefecturesResponse,
  ProductImagePostRequest,
  ProductImageResponse,
  ProductListResponse,
  ProductLowStockResponse,
  ProductPatchRequest,
  ProductRankingResponse,
  ProductResponse,
  ProductStockPatchRequest,
  ProductsCategoriesResponse,
  ProductsPostRequest,
  ProductsStatusesResponse,
  PurchaseAggregateResponse,
  PurchaseCancelResponse,
  PurchaseDeliverResponse,
  PurchaseGetDetailResponse,
  PurchaseListResponse,
  PurchasePayResponse,
  PurchaseResponse,
  PurchaseShippableResponse,
  PurchaseShipResponse,
  PurchasesPostRequest,
  ServiceUnavailable503Response,
  Unauthorized401Response,
  UnprocessableEntity422Response,
  UnsupportedMediaType415Response,
  UserPatchRequest,
  UserPutRequest,
  UserResponse,
  UsersFeedResponse,
  UsersPostRequest,
  UsersResponse,
  UsersSearchResponse,
} from "../../src/adapters/gen/api/model";

export type getUsersResponse200 = {
  data: UsersResponse;
  status: 200;
};

export type getUsersResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getUsersResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getUsersResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type getUsersResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getUsersResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getUsersResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getUsersResponseSuccess = getUsersResponse200 & {
  headers: Headers;
};
export type getUsersResponseError = (
  | getUsersResponse400
  | getUsersResponse401
  | getUsersResponse403
  | getUsersResponse405
  | getUsersResponse500
  | getUsersResponse503
) & {
  headers: Headers;
};

export type getUsersResponse = getUsersResponseSuccess | getUsersResponseError;

export const getGetUsersUrl = (params?: GetUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/users?${stringifiedParams}` : `/v1/users`;
};

/**
 * ユーザーの一覧を取得します。ページネーションを指定できます。
 * @summary ユーザー一覧の取得
 */
export const getUsers = async (
  params?: GetUsersParams,
  options?: RequestInit,
): Promise<getUsersResponse> => {
  const res = await fetch(getGetUsersUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUsersResponse;
};

export type postUsersResponse201 = {
  data: UserResponse;
  status: 201;
};

export type postUsersResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type postUsersResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type postUsersResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type postUsersResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type postUsersResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type postUsersResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type postUsersResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type postUsersResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type postUsersResponseSuccess = postUsersResponse201 & {
  headers: Headers;
};
export type postUsersResponseError = (
  | postUsersResponse400
  | postUsersResponse401
  | postUsersResponse403
  | postUsersResponse405
  | postUsersResponse409
  | postUsersResponse422
  | postUsersResponse500
  | postUsersResponse503
) & {
  headers: Headers;
};

export type postUsersResponse = postUsersResponseSuccess | postUsersResponseError;

export const getPostUsersUrl = () => {
  return `/v1/users`;
};

/**
 * 新しいユーザーを作成します。必要な情報をリクエストボディに含めてください。
 * @summary ユーザーの作成
 */
export const postUsers = async (
  usersPostRequest: UsersPostRequest,
  options?: RequestInit,
): Promise<postUsersResponse> => {
  const res = await fetch(getPostUsersUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(usersPostRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUsersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postUsersResponse;
};

export type getUsersDetailResponse200 = {
  data: UserResponse;
  status: 200;
};

export type getUsersDetailResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getUsersDetailResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getUsersDetailResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type getUsersDetailResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type getUsersDetailResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getUsersDetailResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getUsersDetailResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getUsersDetailResponseSuccess = getUsersDetailResponse200 & {
  headers: Headers;
};
export type getUsersDetailResponseError = (
  | getUsersDetailResponse400
  | getUsersDetailResponse401
  | getUsersDetailResponse403
  | getUsersDetailResponse404
  | getUsersDetailResponse405
  | getUsersDetailResponse500
  | getUsersDetailResponse503
) & {
  headers: Headers;
};

export type getUsersDetailResponse = getUsersDetailResponseSuccess | getUsersDetailResponseError;

export const getGetUsersDetailUrl = (userId: string) => {
  return `/v1/users/${userId}`;
};

/**
 * 指定されたUUIDに該当するユーザーの詳細情報を取得します。
 * @summary 単一ユーザーの取得
 */
export const getUsersDetail = async (
  userId: string,
  options?: RequestInit,
): Promise<getUsersDetailResponse> => {
  const res = await fetch(getGetUsersDetailUrl(userId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersDetailResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUsersDetailResponse;
};

export type putUsersDetailResponse200 = {
  data: UserResponse;
  status: 200;
};

export type putUsersDetailResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type putUsersDetailResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type putUsersDetailResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type putUsersDetailResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type putUsersDetailResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type putUsersDetailResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type putUsersDetailResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type putUsersDetailResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type putUsersDetailResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type putUsersDetailResponseSuccess = putUsersDetailResponse200 & {
  headers: Headers;
};
export type putUsersDetailResponseError = (
  | putUsersDetailResponse400
  | putUsersDetailResponse401
  | putUsersDetailResponse403
  | putUsersDetailResponse404
  | putUsersDetailResponse405
  | putUsersDetailResponse409
  | putUsersDetailResponse422
  | putUsersDetailResponse500
  | putUsersDetailResponse503
) & {
  headers: Headers;
};

export type putUsersDetailResponse = putUsersDetailResponseSuccess | putUsersDetailResponseError;

export const getPutUsersDetailUrl = (userId: string) => {
  return `/v1/users/${userId}`;
};

/**
 * 指定されたUUIDに該当するユーザーの情報を更新します。必要な情報をリクエストボディに含めてください。
 * @summary 単一ユーザーの更新
 */
export const putUsersDetail = async (
  userId: string,
  userPutRequest: UserPutRequest,
  options?: RequestInit,
): Promise<putUsersDetailResponse> => {
  const res = await fetch(getPutUsersDetailUrl(userId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userPutRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putUsersDetailResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as putUsersDetailResponse;
};

export type patchUsersDetailResponse200 = {
  data: UserResponse;
  status: 200;
};

export type patchUsersDetailResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type patchUsersDetailResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type patchUsersDetailResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type patchUsersDetailResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type patchUsersDetailResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type patchUsersDetailResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type patchUsersDetailResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type patchUsersDetailResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type patchUsersDetailResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type patchUsersDetailResponseSuccess = patchUsersDetailResponse200 & {
  headers: Headers;
};
export type patchUsersDetailResponseError = (
  | patchUsersDetailResponse400
  | patchUsersDetailResponse401
  | patchUsersDetailResponse403
  | patchUsersDetailResponse404
  | patchUsersDetailResponse405
  | patchUsersDetailResponse409
  | patchUsersDetailResponse422
  | patchUsersDetailResponse500
  | patchUsersDetailResponse503
) & {
  headers: Headers;
};

export type patchUsersDetailResponse =
  | patchUsersDetailResponseSuccess
  | patchUsersDetailResponseError;

export const getPatchUsersDetailUrl = (userId: string) => {
  return `/v1/users/${userId}`;
};

/**
 * 指定されたUUIDに該当するユーザーの情報を部分的に更新します。必要な情報をリクエストボディに含めてください。
 * @summary 単一ユーザーの部分更新
 */
export const patchUsersDetail = async (
  userId: string,
  userPatchRequest: UserPatchRequest,
  options?: RequestInit,
): Promise<patchUsersDetailResponse> => {
  const res = await fetch(getPatchUsersDetailUrl(userId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userPatchRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchUsersDetailResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as patchUsersDetailResponse;
};

export type deleteUsersDetailResponse204 = {
  data: void;
  status: 204;
};

export type deleteUsersDetailResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type deleteUsersDetailResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type deleteUsersDetailResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type deleteUsersDetailResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type deleteUsersDetailResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type deleteUsersDetailResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type deleteUsersDetailResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type deleteUsersDetailResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type deleteUsersDetailResponseSuccess = deleteUsersDetailResponse204 & {
  headers: Headers;
};
export type deleteUsersDetailResponseError = (
  | deleteUsersDetailResponse400
  | deleteUsersDetailResponse401
  | deleteUsersDetailResponse403
  | deleteUsersDetailResponse404
  | deleteUsersDetailResponse405
  | deleteUsersDetailResponse409
  | deleteUsersDetailResponse500
  | deleteUsersDetailResponse503
) & {
  headers: Headers;
};

export type deleteUsersDetailResponse =
  | deleteUsersDetailResponseSuccess
  | deleteUsersDetailResponseError;

export const getDeleteUsersDetailUrl = (userId: string) => {
  return `/v1/users/${userId}`;
};

/**
 * ユーザーを退会させます。認証必須で、管理者（admin）または本人のみ実行できます。
 * ユーザーを論理削除し、同時に退会イベントを発行します（両者は同一トランザクションで、
 * 退会だけが成立してイベントが失われることはありません）。
 * 退会に伴う関連データの後始末は、このイベントを受け取る側で結果整合として行います。
 * 進行中の購入（完了 / キャンセル / 配達済みのいずれでもない購入）が 1 件でも残っている場合は
 * 409 で拒否します。退会済みユーザーおよび存在しないユーザーは 404 を返します。
 * 管理者でない主体が他ユーザーを退会させようとした場合は 403 で拒否します。
 * @summary ユーザーの退会
 */
export const deleteUsersDetail = async (
  userId: string,
  options?: RequestInit,
): Promise<deleteUsersDetailResponse> => {
  const res = await fetch(getDeleteUsersDetailUrl(userId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUsersDetailResponse["data"] = body ? JSON.parse(body) : undefined;
  return { data, status: res.status, headers: res.headers } as deleteUsersDetailResponse;
};

export type getUsersMeResponse200 = {
  data: UserResponse;
  status: 200;
};

export type getUsersMeResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getUsersMeResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type getUsersMeResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getUsersMeResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getUsersMeResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getUsersMeResponseSuccess = getUsersMeResponse200 & {
  headers: Headers;
};
export type getUsersMeResponseError = (
  | getUsersMeResponse401
  | getUsersMeResponse404
  | getUsersMeResponse405
  | getUsersMeResponse500
  | getUsersMeResponse503
) & {
  headers: Headers;
};

export type getUsersMeResponse = getUsersMeResponseSuccess | getUsersMeResponseError;

export const getGetUsersMeUrl = () => {
  return `/v1/users/me`;
};

/**
 * 認証コンテキスト（Bearer トークン）の内部 UserID に該当するユーザー自身の詳細情報を取得します。
 * @summary 認証ユーザー自身の取得
 */
export const getUsersMe = async (options?: RequestInit): Promise<getUsersMeResponse> => {
  const res = await fetch(getGetUsersMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersMeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUsersMeResponse;
};

export type getUsersMePurchasesSummaryResponse200 = {
  data: PurchaseAggregateResponse;
  status: 200;
};

export type getUsersMePurchasesSummaryResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getUsersMePurchasesSummaryResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getUsersMePurchasesSummaryResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getUsersMePurchasesSummaryResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getUsersMePurchasesSummaryResponseSuccess = getUsersMePurchasesSummaryResponse200 & {
  headers: Headers;
};
export type getUsersMePurchasesSummaryResponseError = (
  | getUsersMePurchasesSummaryResponse401
  | getUsersMePurchasesSummaryResponse405
  | getUsersMePurchasesSummaryResponse500
  | getUsersMePurchasesSummaryResponse503
) & {
  headers: Headers;
};

export type getUsersMePurchasesSummaryResponse =
  | getUsersMePurchasesSummaryResponseSuccess
  | getUsersMePurchasesSummaryResponseError;

export const getGetUsersMePurchasesSummaryUrl = () => {
  return `/v1/users/me/purchases/summary`;
};

/**
 * 認証コンテキスト（Bearer トークン）の内部 UserID に該当するユーザー自身の購入を集計して取得します。
 * マイページの集計カード表示を想定した最小集計で、購入一覧そのものは返しません（履歴は購入履歴一覧 API）。
 * パスに他者の識別子を持たないため、他ユーザーの集計は取得できません。
 * 合計金額は USD セント単位の整数です。キャンセル済みの購入も総件数・合計金額に含めます
 * （キャンセルはステータス別内訳の 1 要素として件数・金額とも返るため、キャンセルを除いた値が必要な
 * クライアントは内訳から差し引けます）。
 * 購入が 1 件もない場合はエラーではなくゼロ値（件数 0・合計 0・内訳は空配列）を返します。
 * 本 op 自体は DB の集計 SELECT のみで外部依存を持ちませんが、認証段（外部 IdP の JWKS 参照）の
 * 一時障害で応答不能となり得るため、認証必須 op の先例に倣い 503 を宣言します。
 * @summary 認証ユーザー自身の購入集計の取得
 */
export const getUsersMePurchasesSummary = async (
  options?: RequestInit,
): Promise<getUsersMePurchasesSummaryResponse> => {
  const res = await fetch(getGetUsersMePurchasesSummaryUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersMePurchasesSummaryResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUsersMePurchasesSummaryResponse;
};

export type getUsersSearchResponse200 = {
  data: UsersSearchResponse;
  status: 200;
};

export type getUsersSearchResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getUsersSearchResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getUsersSearchResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type getUsersSearchResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getUsersSearchResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getUsersSearchResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getUsersSearchResponseSuccess = getUsersSearchResponse200 & {
  headers: Headers;
};
export type getUsersSearchResponseError = (
  | getUsersSearchResponse400
  | getUsersSearchResponse401
  | getUsersSearchResponse403
  | getUsersSearchResponse405
  | getUsersSearchResponse500
  | getUsersSearchResponse503
) & {
  headers: Headers;
};

export type getUsersSearchResponse = getUsersSearchResponseSuccess | getUsersSearchResponseError;

export const getGetUsersSearchUrl = (params?: GetUsersSearchParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/users/search?${stringifiedParams}`
    : `/v1/users/search`;
};

/**
 * 検索条件に基づいてユーザーの一覧を取得します。ページネーションを指定できます。
 * @summary ユーザー一覧の取得
 */
export const getUsersSearch = async (
  params?: GetUsersSearchParams,
  options?: RequestInit,
): Promise<getUsersSearchResponse> => {
  const res = await fetch(getGetUsersSearchUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersSearchResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUsersSearchResponse;
};

export type getUsersFeedResponse200 = {
  data: UsersFeedResponse;
  status: 200;
};

export type getUsersFeedResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getUsersFeedResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getUsersFeedResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type getUsersFeedResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getUsersFeedResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getUsersFeedResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getUsersFeedResponseSuccess = getUsersFeedResponse200 & {
  headers: Headers;
};
export type getUsersFeedResponseError = (
  | getUsersFeedResponse400
  | getUsersFeedResponse401
  | getUsersFeedResponse403
  | getUsersFeedResponse405
  | getUsersFeedResponse500
  | getUsersFeedResponse503
) & {
  headers: Headers;
};

export type getUsersFeedResponse = getUsersFeedResponseSuccess | getUsersFeedResponseError;

export const getGetUsersFeedUrl = (params?: GetUsersFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/users/feed?${stringifiedParams}` : `/v1/users/feed`;
};

/**
 * 未削除のユーザーを作成日時の降順（cursor ページネーション）で取得します。先頭ページは after を省略し、以降は前ページのレスポンスに含まれる nextCursor を after に指定します。
 * @summary ユーザーフィードの取得
 */
export const getUsersFeed = async (
  params?: GetUsersFeedParams,
  options?: RequestInit,
): Promise<getUsersFeedResponse> => {
  const res = await fetch(getGetUsersFeedUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersFeedResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUsersFeedResponse;
};

export type getPrefecturesResponse200 = {
  data: PrefecturesResponse;
  status: 200;
};

export type getPrefecturesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getPrefecturesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getPrefecturesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getPrefecturesResponseSuccess = getPrefecturesResponse200 & {
  headers: Headers;
};
export type getPrefecturesResponseError = (
  | getPrefecturesResponse405
  | getPrefecturesResponse500
  | getPrefecturesResponse503
) & {
  headers: Headers;
};

export type getPrefecturesResponse = getPrefecturesResponseSuccess | getPrefecturesResponseError;

export const getGetPrefecturesUrl = () => {
  return `/v1/prefectures`;
};

/**
 * 都道府県マスタの全件を code 昇順で返します。
 * 認証不要の公開エンドポイントであり、ページネーションは行いません（全 47 件を返します）。
 * @summary 都道府県マスタ一覧の取得
 */
export const getPrefectures = async (options?: RequestInit): Promise<getPrefecturesResponse> => {
  const res = await fetch(getGetPrefecturesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPrefecturesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getPrefecturesResponse;
};

export type getProductStatusesResponse200 = {
  data: ProductsStatusesResponse;
  status: 200;
};

export type getProductStatusesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getProductStatusesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getProductStatusesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getProductStatusesResponseSuccess = getProductStatusesResponse200 & {
  headers: Headers;
};
export type getProductStatusesResponseError = (
  | getProductStatusesResponse405
  | getProductStatusesResponse500
  | getProductStatusesResponse503
) & {
  headers: Headers;
};

export type getProductStatusesResponse =
  | getProductStatusesResponseSuccess
  | getProductStatusesResponseError;

export const getGetProductStatusesUrl = () => {
  return `/v1/products/statuses`;
};

/**
 * 商品ステータスマスタの全件を sortKey（表示順）昇順で返します。
 * 認証不要の公開エンドポイントであり、ページネーションは行いません（全 10 件を返します）。
 * @summary 商品ステータスマスタ一覧の取得
 */
export const getProductStatuses = async (
  options?: RequestInit,
): Promise<getProductStatusesResponse> => {
  const res = await fetch(getGetProductStatusesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductStatusesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getProductStatusesResponse;
};

export type getProductCategoriesResponse200 = {
  data: ProductsCategoriesResponse;
  status: 200;
};

export type getProductCategoriesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getProductCategoriesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getProductCategoriesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getProductCategoriesResponseSuccess = getProductCategoriesResponse200 & {
  headers: Headers;
};
export type getProductCategoriesResponseError = (
  | getProductCategoriesResponse405
  | getProductCategoriesResponse500
  | getProductCategoriesResponse503
) & {
  headers: Headers;
};

export type getProductCategoriesResponse =
  | getProductCategoriesResponseSuccess
  | getProductCategoriesResponseError;

export const getGetProductCategoriesUrl = () => {
  return `/v1/products/categories`;
};

/**
 * 商品カテゴリマスタの全件を sortKey（表示順）昇順で返します。
 * 認証不要の公開エンドポイントであり、ページネーションは行いません（全件を返します）。
 * @summary 商品カテゴリマスタ一覧の取得
 */
export const getProductCategories = async (
  options?: RequestInit,
): Promise<getProductCategoriesResponse> => {
  const res = await fetch(getGetProductCategoriesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductCategoriesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getProductCategoriesResponse;
};

export type getProductsResponse200 = {
  data: ProductListResponse;
  status: 200;
};

export type getProductsResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getProductsResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getProductsResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getProductsResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getProductsResponseSuccess = getProductsResponse200 & {
  headers: Headers;
};
export type getProductsResponseError = (
  | getProductsResponse400
  | getProductsResponse405
  | getProductsResponse500
  | getProductsResponse503
) & {
  headers: Headers;
};

export type getProductsResponse = getProductsResponseSuccess | getProductsResponseError;

export const getGetProductsUrl = (params?: GetProductsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/products?${stringifiedParams}` : `/v1/products`;
};

/**
 * 公開済みの商品を cursor ページネーションで取得します。認証不要の公開エンドポイントです。
 * 既定では公開日時の降順（publishedAt DESC, id DESC）で並び、sort=publishedAt で昇順に切り替えられます。
 * categoryId / statusId でフィルタ、keyword で商品名・説明の部分一致検索ができます。
 * 公開日時が未設定（未公開）の商品は返しません。ステータスによる可視範囲の絞り込みは今後対応予定です。
 * price は USD セント単位の整数です。
 * @summary 商品一覧の取得
 */
export const getProducts = async (
  params?: GetProductsParams,
  options?: RequestInit,
): Promise<getProductsResponse> => {
  const res = await fetch(getGetProductsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getProductsResponse;
};

export type postProductsResponse201 = {
  data: ProductResponse;
  status: 201;
};

export type postProductsResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type postProductsResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type postProductsResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type postProductsResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type postProductsResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type postProductsResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type postProductsResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type postProductsResponseSuccess = postProductsResponse201 & {
  headers: Headers;
};
export type postProductsResponseError = (
  | postProductsResponse400
  | postProductsResponse401
  | postProductsResponse403
  | postProductsResponse405
  | postProductsResponse422
  | postProductsResponse500
  | postProductsResponse503
) & {
  headers: Headers;
};

export type postProductsResponse = postProductsResponseSuccess | postProductsResponseError;

export const getPostProductsUrl = () => {
  return `/v1/products`;
};

/**
 * 商品を作成します。認証必須（admin のみ・非 admin は 403）。
 * description はリッチテキスト HTML を許容し、そのまま格納します（表示側でサニタイズします）。
 * imagePath には画像アップロード（POST /v1/products/images）で得たパスを渡します。
 * price の非数値は 400、負価格・負在庫・名称長超過などの業務不変条件違反は 422 を返します。
 * @summary 商品の作成
 */
export const postProducts = async (
  productsPostRequest: ProductsPostRequest,
  options?: RequestInit,
): Promise<postProductsResponse> => {
  const res = await fetch(getPostProductsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(productsPostRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postProductsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postProductsResponse;
};

export type getProductsDetailResponse200 = {
  data: ProductResponse;
  status: 200;
};

export type getProductsDetailResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getProductsDetailResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type getProductsDetailResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getProductsDetailResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getProductsDetailResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getProductsDetailResponseSuccess = getProductsDetailResponse200 & {
  headers: Headers;
};
export type getProductsDetailResponseError = (
  | getProductsDetailResponse400
  | getProductsDetailResponse404
  | getProductsDetailResponse405
  | getProductsDetailResponse500
  | getProductsDetailResponse503
) & {
  headers: Headers;
};

export type getProductsDetailResponse =
  | getProductsDetailResponseSuccess
  | getProductsDetailResponseError;

export const getGetProductsDetailUrl = (productId: string) => {
  return `/v1/products/${productId}`;
};

/**
 * 指定された UUID に該当する公開済み商品の詳細情報を取得します。認証不要の公開エンドポイントです。
 * 公開日時が未設定（未公開）の商品、および存在しない商品はいずれも 404 を返し、存在を秘匿します。
 * price は USD セント単位の整数です。statusId / categoryId の名称はマスタ API で解決します。
 * @summary 単一商品の取得
 */
export const getProductsDetail = async (
  productId: string,
  options?: RequestInit,
): Promise<getProductsDetailResponse> => {
  const res = await fetch(getGetProductsDetailUrl(productId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsDetailResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getProductsDetailResponse;
};

export type patchProductsDetailResponse200 = {
  data: ProductResponse;
  status: 200;
};

export type patchProductsDetailResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type patchProductsDetailResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type patchProductsDetailResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type patchProductsDetailResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type patchProductsDetailResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type patchProductsDetailResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type patchProductsDetailResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type patchProductsDetailResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type patchProductsDetailResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type patchProductsDetailResponseSuccess = patchProductsDetailResponse200 & {
  headers: Headers;
};
export type patchProductsDetailResponseError = (
  | patchProductsDetailResponse400
  | patchProductsDetailResponse401
  | patchProductsDetailResponse403
  | patchProductsDetailResponse404
  | patchProductsDetailResponse405
  | patchProductsDetailResponse409
  | patchProductsDetailResponse422
  | patchProductsDetailResponse500
  | patchProductsDetailResponse503
) & {
  headers: Headers;
};

export type patchProductsDetailResponse =
  | patchProductsDetailResponseSuccess
  | patchProductsDetailResponseError;

export const getPatchProductsDetailUrl = (productId: string) => {
  return `/v1/products/${productId}`;
};

/**
 * 指定された UUID に該当する商品の属性を部分更新します。admin のみ実行できます（非 admin は 403）。
 * 送信されたフィールドのみを更新し、未送信のフィールドは現在値を据え置きます。
 * description / stockWarningThreshold / publishedAt / imagePath は null を明示するとクリアします。
 * 公開日時そのものを更新対象とするため、取得系と異なり未公開商品も更新できます。
 * version が DB の現在値と一致しない場合は他者の更新と競合したものとして 409 を返します。
 * 409 は再送では解消しないため、クライアントは再取得してから送り直してください。
 * @summary 単一商品の部分更新
 */
export const patchProductsDetail = async (
  productId: string,
  productPatchRequest: ProductPatchRequest,
  options?: RequestInit,
): Promise<patchProductsDetailResponse> => {
  const res = await fetch(getPatchProductsDetailUrl(productId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(productPatchRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchProductsDetailResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as patchProductsDetailResponse;
};

export type patchProductsStockResponse200 = {
  data: ProductResponse;
  status: 200;
};

export type patchProductsStockResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type patchProductsStockResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type patchProductsStockResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type patchProductsStockResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type patchProductsStockResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type patchProductsStockResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type patchProductsStockResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type patchProductsStockResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type patchProductsStockResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type patchProductsStockResponseSuccess = patchProductsStockResponse200 & {
  headers: Headers;
};
export type patchProductsStockResponseError = (
  | patchProductsStockResponse400
  | patchProductsStockResponse401
  | patchProductsStockResponse403
  | patchProductsStockResponse404
  | patchProductsStockResponse405
  | patchProductsStockResponse409
  | patchProductsStockResponse422
  | patchProductsStockResponse500
  | patchProductsStockResponse503
) & {
  headers: Headers;
};

export type patchProductsStockResponse =
  | patchProductsStockResponseSuccess
  | patchProductsStockResponseError;

export const getPatchProductsStockUrl = (productId: string) => {
  return `/v1/products/${productId}/stock`;
};

/**
 * 指定された UUID に該当する商品の在庫を増減します。認証必須で、管理者（admin）のみ実行できます（非 admin は 403）。
 * delta は符号付きで、正の値で補充、負の値で差し引きます。
 * 増減後の在庫が保持できる範囲（0 以上、32bit 整数の上限以下）を外れる要求は 422 で拒否します。
 * 在庫は相対値で更新するため、同一商品への並行更新は失われず合成されます。
 * 購入による在庫減算と同じ行を更新するため、更新は直列化されます。競合はサーバ側で解消され、
 * 解消できなかった場合のみ一時的な失敗として 503 を返します（クライアントは時間を空けて再送できます）。
 * 直列化を経ても取得後に他の更新が入ったことを検出した場合は 409 を返します。
 * 409 は同じ内容の再送では解消しないため、最新を取得し直してからやり直してください。
 * 在庫更新はバージョンを進めるため、更新前のバージョンを持つ部分更新（PATCH /v1/products/{productId}）は
 * 409 で拒否されます。
 * @summary 商品在庫の補充
 */
export const patchProductsStock = async (
  productId: string,
  productStockPatchRequest: ProductStockPatchRequest,
  options?: RequestInit,
): Promise<patchProductsStockResponse> => {
  const res = await fetch(getPatchProductsStockUrl(productId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(productStockPatchRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchProductsStockResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as patchProductsStockResponse;
};

export type getProductsRankingResponse200 = {
  data: ProductRankingResponse;
  status: 200;
};

export type getProductsRankingResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getProductsRankingResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getProductsRankingResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getProductsRankingResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getProductsRankingResponseSuccess = getProductsRankingResponse200 & {
  headers: Headers;
};
export type getProductsRankingResponseError = (
  | getProductsRankingResponse400
  | getProductsRankingResponse405
  | getProductsRankingResponse500
  | getProductsRankingResponse503
) & {
  headers: Headers;
};

export type getProductsRankingResponse =
  | getProductsRankingResponseSuccess
  | getProductsRankingResponseError;

export const getGetProductsRankingUrl = (params?: GetProductsRankingParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/products/ranking?${stringifiedParams}`
    : `/v1/products/ranking`;
};

/**
 * 購入明細を集計し、販売数量の多い順に商品ランキングを返します。認証不要の公開エンドポイントです。
 * キャンセル済みの購入は集計から除外します。未払いの購入は集計に含みます。
 * period=30d の場合は注文日時が直近30日以内の購入のみを集計します。
 * 同一販売数量の商品は商品 ID の昇順で安定的に並びます。
 * @summary 商品売上ランキングの取得
 */
export const getProductsRanking = async (
  params?: GetProductsRankingParams,
  options?: RequestInit,
): Promise<getProductsRankingResponse> => {
  const res = await fetch(getGetProductsRankingUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsRankingResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getProductsRankingResponse;
};

export type getProductsLowStockResponse200 = {
  data: ProductLowStockResponse;
  status: 200;
};

export type getProductsLowStockResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getProductsLowStockResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getProductsLowStockResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type getProductsLowStockResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getProductsLowStockResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getProductsLowStockResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getProductsLowStockResponseSuccess = getProductsLowStockResponse200 & {
  headers: Headers;
};
export type getProductsLowStockResponseError = (
  | getProductsLowStockResponse400
  | getProductsLowStockResponse401
  | getProductsLowStockResponse403
  | getProductsLowStockResponse405
  | getProductsLowStockResponse500
  | getProductsLowStockResponse503
) & {
  headers: Headers;
};

export type getProductsLowStockResponse =
  | getProductsLowStockResponseSuccess
  | getProductsLowStockResponseError;

export const getGetProductsLowStockUrl = (params?: GetProductsLowStockParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/products/low-stock?${stringifiedParams}`
    : `/v1/products/low-stock`;
};

/**
 * 在庫数が在庫警告閾値以下まで減った商品を、在庫の少ない順に上位 limit 件返します。認証必須で、
 * 管理者（admin）のみ実行できます。管理者でなければ 403 で拒否します。
 * 在庫警告閾値が未設定の商品は警告対象外として除外します。閾値ちょうどの商品は警告対象に含みます。
 * 補充の要否は公開状態に依存しないため、未公開の商品も対象に含みます。
 * 同一在庫数の商品は商品 ID の昇順で安定的に並びます。ページネーションは行わず、上位 limit 件のみを返します。
 * 対象商品がない場合はエラーではなく空配列を返します。
 * 本 op 自体は DB の SELECT のみで外部依存を持ちませんが、認証段（外部 IdP の JWKS 参照）の
 * 一時障害で応答不能となり得るため、認証必須 op の先例に倣い 503 を宣言します。
 * @summary 在庫僅少商品一覧の取得
 */
export const getProductsLowStock = async (
  params?: GetProductsLowStockParams,
  options?: RequestInit,
): Promise<getProductsLowStockResponse> => {
  const res = await fetch(getGetProductsLowStockUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsLowStockResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getProductsLowStockResponse;
};

export type postProductsImagesResponse201 = {
  data: ProductImageResponse;
  status: 201;
};

export type postProductsImagesResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type postProductsImagesResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type postProductsImagesResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type postProductsImagesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type postProductsImagesResponse413 = {
  data: PayloadTooLarge413Response;
  status: 413;
};

export type postProductsImagesResponse415 = {
  data: UnsupportedMediaType415Response;
  status: 415;
};

export type postProductsImagesResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type postProductsImagesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type postProductsImagesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type postProductsImagesResponseSuccess = postProductsImagesResponse201 & {
  headers: Headers;
};
export type postProductsImagesResponseError = (
  | postProductsImagesResponse400
  | postProductsImagesResponse401
  | postProductsImagesResponse403
  | postProductsImagesResponse405
  | postProductsImagesResponse413
  | postProductsImagesResponse415
  | postProductsImagesResponse422
  | postProductsImagesResponse500
  | postProductsImagesResponse503
) & {
  headers: Headers;
};

export type postProductsImagesResponse =
  | postProductsImagesResponseSuccess
  | postProductsImagesResponseError;

export const getPostProductsImagesUrl = () => {
  return `/v1/products/images`;
};

/**
 * admin が商品画像をアップロードし、格納先のパスを取得します。認証必須（admin のみ・非 admin は 403）。
 * 返却された imagePath を商品作成 / 更新の imagePath に渡します。表示 URL はフロントが配信ベース URL と
 * 組み立てます。対応形式は png / jpeg / webp、サイズ上限は OBJECT_STORAGE_MAX_UPLOAD_BYTES です
 * （超過は 413、非対応形式は 415、空ファイル等は 422）。
 * @summary 商品画像のアップロード
 */
export const postProductsImages = async (
  productImagePostRequest: ProductImagePostRequest,
  options?: RequestInit,
): Promise<postProductsImagesResponse> => {
  const formData = new FormData();
  formData.append(`image`, productImagePostRequest.image);

  const res = await fetch(getPostProductsImagesUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postProductsImagesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postProductsImagesResponse;
};

export type getExchangeRatesResponse200 = {
  data: ExchangeRateResponse;
  status: 200;
};

export type getExchangeRatesResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getExchangeRatesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getExchangeRatesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getExchangeRatesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getExchangeRatesResponseSuccess = getExchangeRatesResponse200 & {
  headers: Headers;
};
export type getExchangeRatesResponseError = (
  | getExchangeRatesResponse400
  | getExchangeRatesResponse405
  | getExchangeRatesResponse500
  | getExchangeRatesResponse503
) & {
  headers: Headers;
};

export type getExchangeRatesResponse =
  | getExchangeRatesResponseSuccess
  | getExchangeRatesResponseError;

export const getGetExchangeRatesUrl = (params: GetExchangeRatesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/exchange-rates?${stringifiedParams}`
    : `/v1/exchange-rates`;
};

/**
 * base 通貨建ての amount を quote 通貨へ換算した結果を返します。
 * 外部の為替レートサービスを gateway（DTO モード）経由で利用するサンプルエンドポイントです。
 * @summary 為替レートで金額を換算します。
 */
export const getExchangeRates = async (
  params: GetExchangeRatesParams,
  options?: RequestInit,
): Promise<getExchangeRatesResponse> => {
  const res = await fetch(getGetExchangeRatesUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getExchangeRatesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getExchangeRatesResponse;
};

export type getAddressesResponse200 = {
  data: AddressCandidatesResponse;
  status: 200;
};

export type getAddressesResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getAddressesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getAddressesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getAddressesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getAddressesResponseSuccess = getAddressesResponse200 & {
  headers: Headers;
};
export type getAddressesResponseError = (
  | getAddressesResponse400
  | getAddressesResponse405
  | getAddressesResponse500
  | getAddressesResponse503
) & {
  headers: Headers;
};

export type getAddressesResponse = getAddressesResponseSuccess | getAddressesResponseError;

export const getGetAddressesUrl = (params: GetAddressesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/addresses?${stringifiedParams}` : `/v1/addresses`;
};

/**
 * 郵便番号（postalCode）から住所候補（都道府県・市区町村・町域）を補完して返します。
 * 外部の郵便番号 lookup サービスを gateway（DTO モード）経由で利用するサンプルエンドポイントです。
 * 登録画面（郵便番号入力→住所オートフィル）で利用するため認証不要で、外部 lookup 障害時は
 * 503 ではなく `200 + 空 candidates + isFallback: true` で degrade します（外部が落ちても登録を止めない）。
 * @summary 郵便番号から住所候補を補完します。
 */
export const getAddresses = async (
  params: GetAddressesParams,
  options?: RequestInit,
): Promise<getAddressesResponse> => {
  const res = await fetch(getGetAddressesUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAddressesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getAddressesResponse;
};

export type getPurchasesResponse200 = {
  data: PurchaseListResponse;
  status: 200;
};

export type getPurchasesResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getPurchasesResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getPurchasesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getPurchasesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getPurchasesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getPurchasesResponseSuccess = getPurchasesResponse200 & {
  headers: Headers;
};
export type getPurchasesResponseError = (
  | getPurchasesResponse400
  | getPurchasesResponse401
  | getPurchasesResponse405
  | getPurchasesResponse500
  | getPurchasesResponse503
) & {
  headers: Headers;
};

export type getPurchasesResponse = getPurchasesResponseSuccess | getPurchasesResponseError;

export const getGetPurchasesUrl = (params?: GetPurchasesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/purchases?${stringifiedParams}` : `/v1/purchases`;
};

/**
 * 認証主体（自分）の購入履歴を cursor ページネーションで取得します。認証必須です。
 * 注文日時の降順（orderedAt DESC, id DESC）で安定して並び、前ページのレスポンスに含まれる
 * nextCursor を after に渡して次ページを取得します（無限スクロール）。
 * 一覧は概要（code / totalAmount / status / orderedAt）のみを返し、明細は含みません。
 * 他ユーザーの購入は返しません（所有権フィルタで閉じるため、対象がなければ空一覧です）。
 * totalAmount は USD セント単位の整数です。
 * @summary 購入履歴一覧の取得
 */
export const getPurchases = async (
  params?: GetPurchasesParams,
  options?: RequestInit,
): Promise<getPurchasesResponse> => {
  const res = await fetch(getGetPurchasesUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPurchasesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getPurchasesResponse;
};

export type postPurchasesResponse201 = {
  data: PurchaseResponse;
  status: 201;
};

export type postPurchasesResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type postPurchasesResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type postPurchasesResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type postPurchasesResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type postPurchasesResponse422 = {
  data: UnprocessableEntity422Response;
  status: 422;
};

export type postPurchasesResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type postPurchasesResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type postPurchasesResponseSuccess = postPurchasesResponse201 & {
  headers: Headers;
};
export type postPurchasesResponseError = (
  | postPurchasesResponse400
  | postPurchasesResponse401
  | postPurchasesResponse405
  | postPurchasesResponse409
  | postPurchasesResponse422
  | postPurchasesResponse500
  | postPurchasesResponse503
) & {
  headers: Headers;
};

export type postPurchasesResponse = postPurchasesResponseSuccess | postPurchasesResponseError;

export const getPostPurchasesUrl = (params?: PostPurchasesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/purchases?${stringifiedParams}` : `/v1/purchases`;
};

/**
 * 明細（商品IDと数量）の配列から購入を作成します。認証必須です。
 * 在庫減算・購入作成・明細作成を単一トランザクションで原子的に行い、在庫不足（売り越し）は 409 で
 * 購入を成立させません。明細の空配列・同一 productId の重複は 422 です。
 * 退会が確定済みのユーザーは認証の時点で 401 です。受付から成立までの間に退会が確定した場合のみ 409 になります。
 * Idempotency-Key により二重 POST を冪等化します。金額はすべて USD セント単位の整数です。
 * displayCurrency 指定時は合計金額の参考換算額（referenceAmount）を返します（非永続・レート障害時は null）。
 * @summary 購入の作成
 */
export const postPurchases = async (
  purchasesPostRequest: PurchasesPostRequest,
  params?: PostPurchasesParams,
  options?: RequestInit,
): Promise<postPurchasesResponse> => {
  const res = await fetch(getPostPurchasesUrl(params), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(purchasesPostRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postPurchasesResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postPurchasesResponse;
};

export type getPurchasesShippableResponse200 = {
  data: PurchaseShippableResponse;
  status: 200;
};

export type getPurchasesShippableResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getPurchasesShippableResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getPurchasesShippableResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type getPurchasesShippableResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getPurchasesShippableResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getPurchasesShippableResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getPurchasesShippableResponseSuccess = getPurchasesShippableResponse200 & {
  headers: Headers;
};
export type getPurchasesShippableResponseError = (
  | getPurchasesShippableResponse400
  | getPurchasesShippableResponse401
  | getPurchasesShippableResponse403
  | getPurchasesShippableResponse405
  | getPurchasesShippableResponse500
  | getPurchasesShippableResponse503
) & {
  headers: Headers;
};

export type getPurchasesShippableResponse =
  | getPurchasesShippableResponseSuccess
  | getPurchasesShippableResponseError;

export const getGetPurchasesShippableUrl = (params?: GetPurchasesShippableParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/purchases/shippable?${stringifiedParams}`
    : `/v1/purchases/shippable`;
};

/**
 * 発送可能な購入を、まとめて発送してよい組に分けて返します。認証必須で、
 * 管理者（admin）のみ実行できます。管理者でなければ 403 で拒否します。
 * 発送可能とは支払いを終え、まだ発送していない状態です。
 * まとめる軸は同一の購入者で、同じ購入者宛ての購入が 1 つの組になります。購入が 1 件だけの購入者も
 * その 1 件からなる組になります。
 * 組の中は注文日時の古い順（同時刻は購入 ID の昇順）、組同士はその組の最も古い購入の同じ順序で並びます。
 * limit は読み出す購入の件数で、まとめ判定はその範囲の中で行います。範囲の外にある同一購入者の購入は
 * 別の便になります。ページネーションは行わず、上位 limit 件のみを対象とします。
 * 発送待ちの購入がない場合はエラーではなく空配列を返します。
 * 発送の実行は購入 1 件ずつ `POST /v1/purchases/{purchaseId}/ship` で行います。
 * 本 op 自体は DB の SELECT のみで外部依存を持ちませんが、認証段（外部 IdP の JWKS 参照）の
 * 一時障害で応答不能となり得るため、認証必須 op の先例に倣い 503 を宣言します。
 * @summary 発送待ち購入のまとめ発送一覧の取得
 */
export const getPurchasesShippable = async (
  params?: GetPurchasesShippableParams,
  options?: RequestInit,
): Promise<getPurchasesShippableResponse> => {
  const res = await fetch(getGetPurchasesShippableUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPurchasesShippableResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getPurchasesShippableResponse;
};

export type getPurchasesDetailResponse200 = {
  data: PurchaseGetDetailResponse;
  status: 200;
};

export type getPurchasesDetailResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getPurchasesDetailResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type getPurchasesDetailResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getPurchasesDetailResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getPurchasesDetailResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getPurchasesDetailResponseSuccess = getPurchasesDetailResponse200 & {
  headers: Headers;
};
export type getPurchasesDetailResponseError = (
  | getPurchasesDetailResponse401
  | getPurchasesDetailResponse404
  | getPurchasesDetailResponse405
  | getPurchasesDetailResponse500
  | getPurchasesDetailResponse503
) & {
  headers: Headers;
};

export type getPurchasesDetailResponse =
  | getPurchasesDetailResponseSuccess
  | getPurchasesDetailResponseError;

export const getGetPurchasesDetailUrl = (purchaseId: string) => {
  return `/v1/purchases/${purchaseId}`;
};

/**
 * 認証主体（本人）の購入 1 件を明細込みで取得します。認証必須です。
 * status は ID・名称を事前解決済みで、明細には商品名（products との結合で解決した現在名）を含みます。
 * 他ユーザーの購入・不存在はいずれも 404 で存在を秘匿します。
 * 金額（subtotalAmount / taxAmount / shippingFee / totalAmount）はすべて USD セント単位の整数、
 * 明細 unitPrice は購入時点の単価スナップショット（USD ドルの decimal 文字列）です。
 * @summary 購入詳細の取得
 */
export const getPurchasesDetail = async (
  purchaseId: string,
  options?: RequestInit,
): Promise<getPurchasesDetailResponse> => {
  const res = await fetch(getGetPurchasesDetailUrl(purchaseId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPurchasesDetailResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getPurchasesDetailResponse;
};

export type patchPurchasesCancelResponse200 = {
  data: PurchaseCancelResponse;
  status: 200;
};

export type patchPurchasesCancelResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type patchPurchasesCancelResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type patchPurchasesCancelResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type patchPurchasesCancelResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type patchPurchasesCancelResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type patchPurchasesCancelResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type patchPurchasesCancelResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type patchPurchasesCancelResponseSuccess = patchPurchasesCancelResponse200 & {
  headers: Headers;
};
export type patchPurchasesCancelResponseError = (
  | patchPurchasesCancelResponse400
  | patchPurchasesCancelResponse401
  | patchPurchasesCancelResponse404
  | patchPurchasesCancelResponse405
  | patchPurchasesCancelResponse409
  | patchPurchasesCancelResponse500
  | patchPurchasesCancelResponse503
) & {
  headers: Headers;
};

export type patchPurchasesCancelResponse =
  | patchPurchasesCancelResponseSuccess
  | patchPurchasesCancelResponseError;

export const getPatchPurchasesCancelUrl = (purchaseId: string) => {
  return `/v1/purchases/${purchaseId}/cancel`;
};

/**
 * 認証主体（本人）の購入をキャンセルします。認証必須です。
 * キャンセル可能状態（未処理 / 受付中 / 確認中 / 処理中 / 支払い済み）からのみ遷移でき、
 * status を「キャンセル」へ更新し canceledAt をセットします。完了・キャンセル済み、および
 * 発送済み（shippedAt）・配達済み（deliveredAt）の購入は 409 で拒否します。
 * キャンセル時に購入明細分の在庫を復元します（作成時の在庫減算と対称・同一トランザクションで強整合）。
 * 他ユーザーの購入は 404 で存在を秘匿します。金額はすべて USD セント単位の整数です。
 * @summary 購入のキャンセル
 */
export const patchPurchasesCancel = async (
  purchaseId: string,
  options?: RequestInit,
): Promise<patchPurchasesCancelResponse> => {
  const res = await fetch(getPatchPurchasesCancelUrl(purchaseId), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchPurchasesCancelResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as patchPurchasesCancelResponse;
};

export type patchPurchasesPayResponse200 = {
  data: PurchasePayResponse;
  status: 200;
};

export type patchPurchasesPayResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type patchPurchasesPayResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type patchPurchasesPayResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type patchPurchasesPayResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type patchPurchasesPayResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type patchPurchasesPayResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type patchPurchasesPayResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type patchPurchasesPayResponseSuccess = patchPurchasesPayResponse200 & {
  headers: Headers;
};
export type patchPurchasesPayResponseError = (
  | patchPurchasesPayResponse400
  | patchPurchasesPayResponse401
  | patchPurchasesPayResponse404
  | patchPurchasesPayResponse405
  | patchPurchasesPayResponse409
  | patchPurchasesPayResponse500
  | patchPurchasesPayResponse503
) & {
  headers: Headers;
};

export type patchPurchasesPayResponse =
  | patchPurchasesPayResponseSuccess
  | patchPurchasesPayResponseError;

export const getPatchPurchasesPayUrl = (purchaseId: string) => {
  return `/v1/purchases/${purchaseId}/pay`;
};

/**
 * 認証主体（本人）の購入を支払い済みへ遷移させます。認証必須です。
 * 決済 SDK / PSP 連携は行わず、paidAt のセットと status の「支払い済み」への更新で擬似決済を代替します
 * （金額・決済結果の検証は行いません）。未払い相当（未処理 / 受付中 / 確認中 / 処理中）からのみ遷移でき、
 * 既に支払い済みの購入は 409（二重支払い）、キャンセル済み・完了・発送済み・配達済みの購入は 409（不正遷移）で拒否します。
 * 他ユーザーの購入は 404 で存在を秘匿します。金額はすべて USD セント単位の整数です。
 * @summary 購入の支払い
 */
export const patchPurchasesPay = async (
  purchaseId: string,
  options?: RequestInit,
): Promise<patchPurchasesPayResponse> => {
  const res = await fetch(getPatchPurchasesPayUrl(purchaseId), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchPurchasesPayResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as patchPurchasesPayResponse;
};

export type patchPurchasesShipResponse200 = {
  data: PurchaseShipResponse;
  status: 200;
};

export type patchPurchasesShipResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type patchPurchasesShipResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type patchPurchasesShipResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type patchPurchasesShipResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type patchPurchasesShipResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type patchPurchasesShipResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type patchPurchasesShipResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type patchPurchasesShipResponseSuccess = patchPurchasesShipResponse200 & {
  headers: Headers;
};
export type patchPurchasesShipResponseError = (
  | patchPurchasesShipResponse400
  | patchPurchasesShipResponse401
  | patchPurchasesShipResponse403
  | patchPurchasesShipResponse404
  | patchPurchasesShipResponse405
  | patchPurchasesShipResponse409
  | patchPurchasesShipResponse500
) & {
  headers: Headers;
};

export type patchPurchasesShipResponse =
  | patchPurchasesShipResponseSuccess
  | patchPurchasesShipResponseError;

export const getPatchPurchasesShipUrl = (purchaseId: string) => {
  return `/v1/purchases/${purchaseId}/ship`;
};

/**
 * 購入を発送済みへ遷移させます。認証必須で、管理者（admin）のみ実行できます。
 * 支払い済みからのみ遷移でき、status を「発送済み」へ更新し shippedAt をセットします。
 * 未払い相当（未処理 / 受付中 / 確認中 / 処理中）・完了・キャンセル済み・配達済みの購入は 409（不正遷移）、
 * 既に発送済みの購入も 409（二重発送）で拒否します。配送追跡（追跡番号 / 配送業者 / 追跡 URL）は扱いません。
 * 購入者本人であっても管理者でなければ 403 で拒否します。金額はすべて USD セント単位の整数です。
 * @summary 購入の発送
 */
export const patchPurchasesShip = async (
  purchaseId: string,
  options?: RequestInit,
): Promise<patchPurchasesShipResponse> => {
  const res = await fetch(getPatchPurchasesShipUrl(purchaseId), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchPurchasesShipResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as patchPurchasesShipResponse;
};

export type patchPurchasesDeliverResponse200 = {
  data: PurchaseDeliverResponse;
  status: 200;
};

export type patchPurchasesDeliverResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type patchPurchasesDeliverResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type patchPurchasesDeliverResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type patchPurchasesDeliverResponse404 = {
  data: NotFound404Response;
  status: 404;
};

export type patchPurchasesDeliverResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type patchPurchasesDeliverResponse409 = {
  data: Conflict409Response;
  status: 409;
};

export type patchPurchasesDeliverResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type patchPurchasesDeliverResponseSuccess = patchPurchasesDeliverResponse200 & {
  headers: Headers;
};
export type patchPurchasesDeliverResponseError = (
  | patchPurchasesDeliverResponse400
  | patchPurchasesDeliverResponse401
  | patchPurchasesDeliverResponse403
  | patchPurchasesDeliverResponse404
  | patchPurchasesDeliverResponse405
  | patchPurchasesDeliverResponse409
  | patchPurchasesDeliverResponse500
) & {
  headers: Headers;
};

export type patchPurchasesDeliverResponse =
  | patchPurchasesDeliverResponseSuccess
  | patchPurchasesDeliverResponseError;

export const getPatchPurchasesDeliverUrl = (purchaseId: string) => {
  return `/v1/purchases/${purchaseId}/deliver`;
};

/**
 * 購入を配達済みへ遷移させます。認証必須で、管理者（admin）のみ実行できます。
 * 発送済みからのみ遷移でき、status を「配達済み」へ更新し deliveredAt をセットします。
 * 未払い相当（未処理 / 受付中 / 確認中 / 処理中）・支払い済み（未発送）・完了・キャンセル済みの購入は 409（不正遷移）、
 * 既に配達済みの購入も 409（二重配達）で拒否します。配達確認の証跡（署名 / 受領写真 / GPS 位置）は扱いません。
 * 購入者本人であっても管理者でなければ 403 で拒否します。金額はすべて USD セント単位の整数です。
 * @summary 購入の配達完了
 */
export const patchPurchasesDeliver = async (
  purchaseId: string,
  options?: RequestInit,
): Promise<patchPurchasesDeliverResponse> => {
  const res = await fetch(getPatchPurchasesDeliverUrl(purchaseId), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchPurchasesDeliverResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as patchPurchasesDeliverResponse;
};

export type getDashboardSummaryResponse200 = {
  data: DashboardSummaryResponse;
  status: 200;
};

export type getDashboardSummaryResponse400 = {
  data: BadRequest400Response;
  status: 400;
};

export type getDashboardSummaryResponse401 = {
  data: Unauthorized401Response;
  status: 401;
};

export type getDashboardSummaryResponse403 = {
  data: Forbidden403Response;
  status: 403;
};

export type getDashboardSummaryResponse405 = {
  data: MethodNotAllowed405Response;
  status: 405;
};

export type getDashboardSummaryResponse500 = {
  data: InternalServerError500Response;
  status: 500;
};

export type getDashboardSummaryResponse503 = {
  data: ServiceUnavailable503Response;
  status: 503;
};

export type getDashboardSummaryResponseSuccess = getDashboardSummaryResponse200 & {
  headers: Headers;
};
export type getDashboardSummaryResponseError = (
  | getDashboardSummaryResponse400
  | getDashboardSummaryResponse401
  | getDashboardSummaryResponse403
  | getDashboardSummaryResponse405
  | getDashboardSummaryResponse500
  | getDashboardSummaryResponse503
) & {
  headers: Headers;
};

export type getDashboardSummaryResponse =
  | getDashboardSummaryResponseSuccess
  | getDashboardSummaryResponseError;

export const getGetDashboardSummaryUrl = (params?: GetDashboardSummaryParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/dashboard/summary?${stringifiedParams}`
    : `/v1/dashboard/summary`;
};

/**
 * 購入・商品を横断した集計を 1 レスポンスに合成して返します（1 画面 1 API）。認証必須で、管理者（admin）のみ
 * 実行できます。管理者でなければ 403 で拒否します。数値カード向けの集計値のみを返し、一覧・時系列は含みません。
 * 集計対象期間は period で切り替えます。today / month の境界はサーバのタイムゾーン（Asia/Tokyo）基準で
 * 算出し、range は from / to の暦日をいずれも含む期間として集計します。range で from / to が欠落している
 * 場合、および to が from より前の場合は 400 を返します。
 * 売上（salesAmount / salesCount）はキャンセル済みの購入を除外し未払いの購入を含みます。一方
 * purchaseStatusCounts はキャンセル済みも 1 ステータスとして含むため、両者の母集団は一致しません。
 * 商品数は期間に依存しないマスタの現在値です。金額は USD セント単位の整数です。
 * 対象データがない場合はエラーではなくゼロ値（各件数・金額 0・内訳は空配列）を返します。
 * 本 op 自体は DB の集計 SELECT のみで外部依存を持ちませんが、認証段（外部 IdP の JWKS 参照）の
 * 一時障害で応答不能となり得るため、認証必須 op の先例に倣い 503 を宣言します。
 * @summary admin ダッシュボードの横断集計の取得
 */
export const getDashboardSummary = async (
  params?: GetDashboardSummaryParams,
  options?: RequestInit,
): Promise<getDashboardSummaryResponse> => {
  const res = await fetch(getGetDashboardSummaryUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDashboardSummaryResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getDashboardSummaryResponse;
};
