/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Go Boilerplate API
 * Reference specification for the sample API (users, products, purchases). It exercises every layer
 * of the Onion Architecture end to end: cursor and offset pagination, creation and partial update,
 * soft delete, idempotency keys, and role-based authorization.
 *
 * Handlers (oapi-codegen) and the published reference documentation are both generated from this
 * file, so every endpoint change starts here.
 *
 * OpenAPI spec version: 2.2.0+15463a1
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";

import type {
  AddressCandidatesResponse,
  DashboardSummaryResponse,
  ExchangeRateResponse,
  PrefecturesResponse,
  ProductImageResponse,
  ProductListResponse,
  ProductLowStockResponse,
  ProductRankingResponse,
  ProductResponse,
  ProductsCategoriesResponse,
  ProductsStatusesResponse,
  PurchaseAggregateResponse,
  PurchaseCancelResponse,
  PurchaseDeliverResponse,
  PurchaseGetDetailResponse,
  PurchaseListResponse,
  PurchasePayResponse,
  PurchaseResponse,
  PurchaseShippableResponse,
  PurchaseShipResponse,
  UserResponse,
  UsersFeedResponse,
  UsersResponse,
  UsersSearchResponse,
} from "../../src/adapters/gen/api/model";

export const getGetUsersResponseMock = (): UsersResponse => ({
  ...{
    users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        email: faker.internet.email(),
        phone: (() => "09012345678")(),
        postalCode: (() => "100-0001")(),
        prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
        city: faker.string.alpha({ length: { min: 10, max: 100 } }),
        street: faker.string.alpha({ length: { min: 10, max: 255 } }),
        building: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 255 } }),
          undefined,
        ]),
        deletedAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          null,
        ]),
      }),
    ),
  },
  ...{ total: faker.number.int(), limit: faker.number.int(), offset: faker.number.int() },
});

export const getPostUsersResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
  city: faker.string.alpha({ length: { min: 10, max: 100 } }),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getGetUsersDetailResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
  city: faker.string.alpha({ length: { min: 10, max: 100 } }),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getPutUsersDetailResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
  city: faker.string.alpha({ length: { min: 10, max: 100 } }),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getPatchUsersDetailResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
  city: faker.string.alpha({ length: { min: 10, max: 100 } }),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getGetUsersMeResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
  city: faker.string.alpha({ length: { min: 10, max: 100 } }),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getGetUsersMePurchasesSummaryResponseMock = (
  overrideResponse: Partial<Extract<PurchaseAggregateResponse, object>> = {},
): PurchaseAggregateResponse => ({
  totalCount: faker.number.int(),
  totalAmount: faker.number.int(),
  statusBreakdown: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
    count: faker.number.int(),
    totalAmount: faker.number.int(),
  })),
  ...overrideResponse,
});

export const getGetUsersSearchResponseMock = (): UsersSearchResponse => ({
  ...{
    users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        ...{
          firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
          lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
          email: faker.internet.email(),
          phone: (() => "09012345678")(),
          postalCode: (() => "100-0001")(),
          prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
          city: faker.string.alpha({ length: { min: 10, max: 100 } }),
          street: faker.string.alpha({ length: { min: 10, max: 255 } }),
          building: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 255 } }),
            undefined,
          ]),
          deletedAt: faker.helpers.arrayElement([
            faker.date.past().toISOString().slice(0, 19) + "Z",
            null,
          ]),
        },
        ...{ registeredAt: faker.date.past().toISOString().slice(0, 19) + "Z" },
      }),
    ),
  },
  ...{ total: faker.number.int(), limit: faker.number.int(), offset: faker.number.int() },
});

export const getGetUsersFeedResponseMock = (): UsersFeedResponse => ({
  ...{
    users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        email: faker.internet.email(),
        phone: (() => "09012345678")(),
        postalCode: (() => "100-0001")(),
        prefecture: faker.string.alpha({ length: { min: 10, max: 100 } }),
        city: faker.string.alpha({ length: { min: 10, max: 100 } }),
        street: faker.string.alpha({ length: { min: 10, max: 255 } }),
        building: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 255 } }),
          undefined,
        ]),
        deletedAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          null,
        ]),
      }),
    ),
  },
  ...{
    nextCursor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    hasNext: faker.datatype.boolean(),
  },
});

export const getGetPrefecturesResponseMock = (): PrefecturesResponse =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    code: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  }));

export const getGetProductStatusesResponseMock = (): ProductsStatusesResponse =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    ...{ id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
    ...{ code: faker.number.int(), sortKey: faker.number.int() },
  }));

export const getGetProductCategoriesResponseMock = (): ProductsCategoriesResponse =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    ...{ id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
    ...{ code: faker.number.int(), sortKey: faker.number.int() },
  }));

export const getGetProductsResponseMock = (): ProductListResponse => ({
  ...{
    products: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        id: faker.string.uuid(),
        name: faker.string.alpha({ length: { min: 10, max: 255 } }),
        description: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        price: (() => "19.99")(),
        quantity: faker.number.int(),
        stockWarningThreshold: faker.helpers.arrayElement([faker.number.int(), null]),
        status: {
          id: faker.string.uuid(),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        },
        category: {
          id: faker.string.uuid(),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        },
        publishedAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          null,
        ]),
        images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
          () => ({
            imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
            sortKey: faker.number.int({ min: 1, max: 32767 }),
          }),
        ),
        version: faker.number.int(),
      }),
    ),
  },
  ...{
    nextCursor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    hasNext: faker.datatype.boolean(),
  },
});

export const getPostProductsResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: faker.number.int(),
  stockWarningThreshold: faker.helpers.arrayElement([faker.number.int(), null]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      sortKey: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: faker.number.int(),
  ...overrideResponse,
});

export const getGetProductsDetailResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: faker.number.int(),
  stockWarningThreshold: faker.helpers.arrayElement([faker.number.int(), null]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      sortKey: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: faker.number.int(),
  ...overrideResponse,
});

export const getPatchProductsDetailResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: faker.number.int(),
  stockWarningThreshold: faker.helpers.arrayElement([faker.number.int(), null]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      sortKey: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: faker.number.int(),
  ...overrideResponse,
});

export const getPatchProductsStockResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: faker.number.int(),
  stockWarningThreshold: faker.helpers.arrayElement([faker.number.int(), null]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      sortKey: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: faker.number.int(),
  ...overrideResponse,
});

export const getGetProductsRankingResponseMock = (
  overrideResponse: Partial<Extract<ProductRankingResponse, object>> = {},
): ProductRankingResponse => ({
  rankings: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      name: faker.string.alpha({ length: { min: 10, max: 255 } }),
      price: (() => "19.99")(),
      soldQuantity: faker.number.int(),
    }),
  ),
  ...overrideResponse,
});

export const getGetProductsLowStockResponseMock = (
  overrideResponse: Partial<Extract<ProductLowStockResponse, object>> = {},
): ProductLowStockResponse => ({
  products: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      id: faker.string.uuid(),
      name: faker.string.alpha({ length: { min: 10, max: 255 } }),
      description: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      price: (() => "19.99")(),
      quantity: faker.number.int(),
      stockWarningThreshold: faker.helpers.arrayElement([faker.number.int(), null]),
      status: {
        id: faker.string.uuid(),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      category: {
        id: faker.string.uuid(),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      publishedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        null,
      ]),
      images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
        () => ({
          imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
          sortKey: faker.number.int({ min: 1, max: 32767 }),
        }),
      ),
      version: faker.number.int(),
    }),
  ),
  ...overrideResponse,
});

export const getPostProductsImagesResponseMock = (
  overrideResponse: Partial<Extract<ProductImageResponse, object>> = {},
): ProductImageResponse => ({
  imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetExchangeRatesResponseMock = (
  overrideResponse: Partial<Extract<ExchangeRateResponse, object>> = {},
): ExchangeRateResponse => ({
  base: faker.string.alpha({ length: { min: 10, max: 20 } }),
  quote: faker.string.alpha({ length: { min: 10, max: 20 } }),
  original: (() => "19.99")(),
  converted: (() => "-19.99")(),
  referenceAmount: faker.helpers.arrayElement([
    {
      currency: faker.string.alpha({ length: { min: 10, max: 20 } }),
      amount: faker.number.int(),
      rate: (() => "19.99")(),
      rateDate: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    null,
  ]),
  ...overrideResponse,
});

export const getGetAddressesResponseMock = (
  overrideResponse: Partial<Extract<AddressCandidatesResponse, object>> = {},
): AddressCandidatesResponse => ({
  candidates: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      prefectureId: faker.helpers.arrayElement([faker.string.uuid(), null]),
      prefectureName: faker.string.alpha({ length: { min: 10, max: 20 } }),
      city: faker.string.alpha({ length: { min: 10, max: 20 } }),
      town: faker.string.alpha({ length: { min: 10, max: 20 } }),
    }),
  ),
  isFallback: faker.datatype.boolean(),
  ...overrideResponse,
});

export const getGetPurchasesResponseMock = (): PurchaseListResponse => ({
  ...{
    items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        code: faker.string.alpha({ length: { min: 10, max: 20 } }),
        totalAmount: faker.number.int(),
        status: {
          id: faker.string.uuid(),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        },
        orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      }),
    ),
  },
  ...{
    nextCursor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    hasNext: faker.datatype.boolean(),
  },
});

export const getPostPurchasesResponseMock = (
  overrideResponse: Partial<Extract<PurchaseResponse, object>> = {},
): PurchaseResponse => ({
  id: faker.string.uuid(),
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  statusId: faker.string.uuid(),
  subtotalAmount: faker.number.int(),
  taxAmount: faker.number.int(),
  shippingFee: faker.number.int(),
  totalAmount: faker.number.int(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: faker.number.int(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  referenceAmount: faker.helpers.arrayElement([
    {
      currency: faker.string.alpha({ length: { min: 10, max: 20 } }),
      amount: faker.number.int(),
      rate: (() => "19.99")(),
      rateDate: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    null,
  ]),
  ...overrideResponse,
});

export const getGetPurchasesShippableResponseMock = (
  overrideResponse: Partial<Extract<PurchaseShippableResponse, object>> = {},
): PurchaseShippableResponse => ({
  groups: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      userId: faker.string.uuid(),
      purchases: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
        () => ({
          id: faker.string.uuid(),
          code: faker.string.alpha({ length: { min: 10, max: 20 } }),
          totalAmount: faker.number.int(),
          orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        }),
      ),
    }),
  ),
  ...overrideResponse,
});

export const getGetPurchasesDetailResponseMock = (
  overrideResponse: Partial<Extract<PurchaseGetDetailResponse, object>> = {},
): PurchaseGetDetailResponse => ({
  id: faker.string.uuid(),
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  subtotalAmount: faker.number.int(),
  taxAmount: faker.number.int(),
  shippingFee: faker.number.int(),
  totalAmount: faker.number.int(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      productName: faker.string.alpha({ length: { min: 10, max: 20 } }),
      quantity: faker.number.int(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  paidAt: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
    undefined,
  ]),
  canceledAt: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPatchPurchasesCancelResponseMock = (
  overrideResponse: Partial<Extract<PurchaseCancelResponse, object>> = {},
): PurchaseCancelResponse => ({
  id: faker.string.uuid(),
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  subtotalAmount: faker.number.int(),
  taxAmount: faker.number.int(),
  shippingFee: faker.number.int(),
  totalAmount: faker.number.int(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: faker.number.int(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  canceledAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getPatchPurchasesPayResponseMock = (
  overrideResponse: Partial<Extract<PurchasePayResponse, object>> = {},
): PurchasePayResponse => ({
  id: faker.string.uuid(),
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  subtotalAmount: faker.number.int(),
  taxAmount: faker.number.int(),
  shippingFee: faker.number.int(),
  totalAmount: faker.number.int(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: faker.number.int(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  paidAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getPatchPurchasesShipResponseMock = (
  overrideResponse: Partial<Extract<PurchaseShipResponse, object>> = {},
): PurchaseShipResponse => ({
  id: faker.string.uuid(),
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  subtotalAmount: faker.number.int(),
  taxAmount: faker.number.int(),
  shippingFee: faker.number.int(),
  totalAmount: faker.number.int(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: faker.number.int(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  shippedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getPatchPurchasesDeliverResponseMock = (
  overrideResponse: Partial<Extract<PurchaseDeliverResponse, object>> = {},
): PurchaseDeliverResponse => ({
  id: faker.string.uuid(),
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  subtotalAmount: faker.number.int(),
  taxAmount: faker.number.int(),
  shippingFee: faker.number.int(),
  totalAmount: faker.number.int(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: faker.number.int(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  deliveredAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getGetDashboardSummaryResponseMock = (
  overrideResponse: Partial<Extract<DashboardSummaryResponse, object>> = {},
): DashboardSummaryResponse => ({
  salesAmount: faker.number.int(),
  salesCount: faker.number.int(),
  purchaseStatusCounts: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
    count: faker.number.int(),
  })),
  totalProductCount: faker.number.int(),
  publishedProductCount: faker.number.int(),
  ...overrideResponse,
});

export const getGetUsersMockHandler = (
  overrideResponse?:
    | UsersResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UsersResponse> | UsersResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostUsersMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/users",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostUsersResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetUsersDetailMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPutUsersDetailMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPutUsersDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchUsersDetailMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchUsersDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDeleteUsersDetailMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getGetUsersMeMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/me",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersMeResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersMePurchasesSummaryMockHandler = (
  overrideResponse?:
    | PurchaseAggregateResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseAggregateResponse> | PurchaseAggregateResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/me/purchases/summary",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersMePurchasesSummaryResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersSearchMockHandler = (
  overrideResponse?:
    | UsersSearchResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UsersSearchResponse> | UsersSearchResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/search",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersSearchResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersFeedMockHandler = (
  overrideResponse?:
    | UsersFeedResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UsersFeedResponse> | UsersFeedResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/feed",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersFeedResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPrefecturesMockHandler = (
  overrideResponse?:
    | PrefecturesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PrefecturesResponse> | PrefecturesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/prefectures",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPrefecturesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductStatusesMockHandler = (
  overrideResponse?:
    | ProductsStatusesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductsStatusesResponse> | ProductsStatusesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/statuses",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductStatusesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductCategoriesMockHandler = (
  overrideResponse?:
    | ProductsCategoriesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductsCategoriesResponse> | ProductsCategoriesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/categories",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductCategoriesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsMockHandler = (
  overrideResponse?:
    | ProductListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductListResponse> | ProductListResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostProductsMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/products",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostProductsResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetProductsDetailMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/:productId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchProductsDetailMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/products/:productId",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchProductsDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchProductsStockMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/products/:productId/stock",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchProductsStockResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsRankingMockHandler = (
  overrideResponse?:
    | ProductRankingResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductRankingResponse> | ProductRankingResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/ranking",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsRankingResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsLowStockMockHandler = (
  overrideResponse?:
    | ProductLowStockResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductLowStockResponse> | ProductLowStockResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/low-stock",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsLowStockResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostProductsImagesMockHandler = (
  overrideResponse?:
    | ProductImageResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ProductImageResponse> | ProductImageResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/products/images",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostProductsImagesResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetExchangeRatesMockHandler = (
  overrideResponse?:
    | ExchangeRateResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExchangeRateResponse> | ExchangeRateResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/exchange-rates",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetExchangeRatesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetAddressesMockHandler = (
  overrideResponse?:
    | AddressCandidatesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<AddressCandidatesResponse> | AddressCandidatesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/addresses",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetAddressesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPurchasesMockHandler = (
  overrideResponse?:
    | PurchaseListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseListResponse> | PurchaseListResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/purchases",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPurchasesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostPurchasesMockHandler = (
  overrideResponse?:
    | PurchaseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<PurchaseResponse> | PurchaseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/purchases",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostPurchasesResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetPurchasesShippableMockHandler = (
  overrideResponse?:
    | PurchaseShippableResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseShippableResponse> | PurchaseShippableResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/purchases/shippable",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPurchasesShippableResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPurchasesDetailMockHandler = (
  overrideResponse?:
    | PurchaseGetDetailResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseGetDetailResponse> | PurchaseGetDetailResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/purchases/:purchaseId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPurchasesDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesCancelMockHandler = (
  overrideResponse?:
    | PurchaseCancelResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchaseCancelResponse> | PurchaseCancelResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseId/cancel",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesCancelResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesPayMockHandler = (
  overrideResponse?:
    | PurchasePayResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchasePayResponse> | PurchasePayResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseId/pay",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesPayResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesShipMockHandler = (
  overrideResponse?:
    | PurchaseShipResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchaseShipResponse> | PurchaseShipResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseId/ship",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesShipResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesDeliverMockHandler = (
  overrideResponse?:
    | PurchaseDeliverResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchaseDeliverResponse> | PurchaseDeliverResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseId/deliver",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesDeliverResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetDashboardSummaryMockHandler = (
  overrideResponse?:
    | DashboardSummaryResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<DashboardSummaryResponse> | DashboardSummaryResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/dashboard/summary",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetDashboardSummaryResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getGoBoilerplateAPIMock = () => [
  getGetUsersMockHandler(),
  getPostUsersMockHandler(),
  getGetUsersDetailMockHandler(),
  getPutUsersDetailMockHandler(),
  getPatchUsersDetailMockHandler(),
  getDeleteUsersDetailMockHandler(),
  getGetUsersMeMockHandler(),
  getGetUsersMePurchasesSummaryMockHandler(),
  getGetUsersSearchMockHandler(),
  getGetUsersFeedMockHandler(),
  getGetPrefecturesMockHandler(),
  getGetProductStatusesMockHandler(),
  getGetProductCategoriesMockHandler(),
  getGetProductsMockHandler(),
  getPostProductsMockHandler(),
  getGetProductsDetailMockHandler(),
  getPatchProductsDetailMockHandler(),
  getPatchProductsStockMockHandler(),
  getGetProductsRankingMockHandler(),
  getGetProductsLowStockMockHandler(),
  getPostProductsImagesMockHandler(),
  getGetExchangeRatesMockHandler(),
  getGetAddressesMockHandler(),
  getGetPurchasesMockHandler(),
  getPostPurchasesMockHandler(),
  getGetPurchasesShippableMockHandler(),
  getGetPurchasesDetailMockHandler(),
  getPatchPurchasesCancelMockHandler(),
  getPatchPurchasesPayMockHandler(),
  getPatchPurchasesShipMockHandler(),
  getPatchPurchasesDeliverMockHandler(),
  getGetDashboardSummaryMockHandler(),
];
