/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Go Boilerplate API
 * Reference specification for the sample API (users, products, purchases). It exercises every layer
 * of the Onion Architecture end to end: cursor and offset pagination, creation and partial update,
 * soft delete, idempotency keys, and role-based authorization.
 *
 * Handlers (oapi-codegen) and the published reference documentation are both generated from this
 * file, so every endpoint change starts here.
 *
 * OpenAPI spec version: 2.2.0+7b2778e
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";
import type {
  AddressCandidatesResponse,
  CartMergeResponse,
  CartResponse,
  ControlEvent,
  DashboardSummaryResponse,
  DeliveryEvent,
  ExchangeRateResponse,
  PrefecturesResponse,
  ProductAmountRankingResponse,
  ProductCountResponse,
  ProductImageResponse,
  ProductListResponse,
  ProductLowStockResponse,
  ProductQuantityRankingResponse,
  ProductResponse,
  ProductsCategoriesResponse,
  ProductsStatusesResponse,
  PurchaseAggregateResponse,
  PurchaseCancelResponse,
  PurchaseDeliverResponse,
  PurchaseGetDetailResponse,
  PurchaseListResponse,
  PurchasePayResponse,
  PurchaseResponse,
  PurchaseShippableResponse,
  PurchaseShipResponse,
  PurchasesStatusesResponse,
  UserResponse,
  UserRolesResponse,
  UsersFeedResponse,
  UsersResponse,
  UsersSearchResponse,
} from "../../src/adapters/gen/api/model";
import { CartItemIssue } from "../../src/adapters/gen/api/model";

export const getGetStreamResponseDeliveryEventMock = (
  overrideResponse: Partial<DeliveryEvent> = {},
): DeliveryEvent => ({
  ...{
    eventId: faker.string.uuid(),
    streamId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    sequence: faker.helpers.fromRegExp("^(0|[1-9][0-9]{0,18})$"),
    type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    occurredAt: faker.date.past().toISOString().slice(0, 19) + "Z",
    schemaVersion: faker.number.int({ min: 1 }),
    payload: {},
  },
  ...overrideResponse,
});

export const getGetStreamResponseControlEventMock = (
  overrideResponse: Partial<ControlEvent> = {},
): ControlEvent => ({
  ...{
    action: faker.helpers.arrayElement([
      "RECONNECT",
      "RETRY_LATER",
      "REAUTHENTICATE",
      "RESYNC",
      "STOP",
    ] as const),
    reason: faker.helpers.arrayElement([
      "SERVER_DRAINING",
      "TEMPORARILY_OVERLOADED",
      "AUTH_REFRESH_REQUIRED",
      "AUTHORIZATION_REVOKED",
      "CURSOR_TOO_OLD",
      "STREAM_RECOVERY_FAILED",
    ] as const),
    retryAfterMs: faker.helpers.arrayElement([
      faker.number.int({ min: 0, max: 86400000 }),
      undefined,
    ]),
  },
  ...overrideResponse,
});

export const getGetStreamResponseMock = (): DeliveryEvent | ControlEvent =>
  faker.helpers.arrayElement([
    { ...getGetStreamResponseDeliveryEventMock() },
    { ...getGetStreamResponseControlEventMock() },
  ]);

export const getGetUsersResponseMock = (): UsersResponse => ({
  ...{
    users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        id: faker.string.uuid(),
        firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        email: faker.internet.email(),
        phone: (() => "09012345678")(),
        postalCode: (() => "100-0001")(),
        prefecture: (() => "神奈川県")(),
        city: (() => "横浜市西区")(),
        street: faker.string.alpha({ length: { min: 10, max: 255 } }),
        building: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 255 } }),
          undefined,
        ]),
        deletedAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          null,
        ]),
      }),
    ),
  },
  ...{
    total: (() => faker.number.int({ min: 0, max: 9999 }))(),
    limit: (() => faker.number.int({ min: 10, max: 50 }))(),
    offset: (() => faker.number.int({ min: 0, max: 100 }))(),
  },
});

export const getPostUsersResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  id: faker.string.uuid(),
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: (() => "神奈川県")(),
  city: (() => "横浜市西区")(),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getGetUsersDetailResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  id: faker.string.uuid(),
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: (() => "神奈川県")(),
  city: (() => "横浜市西区")(),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getPutUsersDetailResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  id: faker.string.uuid(),
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: (() => "神奈川県")(),
  city: (() => "横浜市西区")(),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getPatchUsersDetailResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  id: faker.string.uuid(),
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: (() => "神奈川県")(),
  city: (() => "横浜市西区")(),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getGetUsersMeResponseMock = (
  overrideResponse: Partial<Extract<UserResponse, object>> = {},
): UserResponse => ({
  id: faker.string.uuid(),
  firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
  email: faker.internet.email(),
  phone: (() => "09012345678")(),
  postalCode: (() => "100-0001")(),
  prefecture: (() => "神奈川県")(),
  city: (() => "横浜市西区")(),
  street: faker.string.alpha({ length: { min: 10, max: 255 } }),
  building: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 255 } }),
    undefined,
  ]),
  deletedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
  ...overrideResponse,
});

export const getGetUsersMePurchasesSummaryResponseMock = (
  overrideResponse: Partial<Extract<PurchaseAggregateResponse, object>> = {},
): PurchaseAggregateResponse => ({
  totalCount: (() => faker.number.int({ min: 0, max: 9999 }))(),
  totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  itemsTotal: faker.string.alpha({ length: { min: 10, max: 20 } }),
  statusBreakdown: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    status: {
      id: faker.string.uuid(),
      code: faker.number.int(),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    count: (() => faker.number.int({ min: 0, max: 9999 }))(),
    totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  })),
  groups: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: {
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        itemsTotal: faker.string.alpha({ length: { min: 10, max: 20 } }),
        groups: faker.helpers.arrayElement([
          {
            [faker.string.alphanumeric(5)]: {
              name: faker.string.alpha({ length: { min: 10, max: 20 } }),
              itemsTotal: faker.string.alpha({ length: { min: 10, max: 20 } }),
            },
          },
          undefined,
        ]),
      },
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetUsersMeRolesResponseMock = (
  overrideResponse: Partial<Extract<UserRolesResponse, object>> = {},
): UserRolesResponse => ({
  roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    code: faker.helpers.arrayElement(["admin", "general"] as const),
    name: faker.string.alpha({ length: { min: 10, max: 100 } }),
  })),
  ...overrideResponse,
});

export const getGetUsersSearchResponseMock = (): UsersSearchResponse => ({
  ...{
    users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        ...{
          id: faker.string.uuid(),
          firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
          lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
          email: faker.internet.email(),
          phone: (() => "09012345678")(),
          postalCode: (() => "100-0001")(),
          prefecture: (() => "神奈川県")(),
          city: (() => "横浜市西区")(),
          street: faker.string.alpha({ length: { min: 10, max: 255 } }),
          building: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 255 } }),
            undefined,
          ]),
          deletedAt: faker.helpers.arrayElement([
            faker.date.past().toISOString().slice(0, 19) + "Z",
            null,
          ]),
        },
        ...{ registeredAt: faker.date.past().toISOString().slice(0, 19) + "Z" },
      }),
    ),
  },
  ...{
    total: (() => faker.number.int({ min: 0, max: 9999 }))(),
    limit: (() => faker.number.int({ min: 10, max: 50 }))(),
    offset: (() => faker.number.int({ min: 0, max: 100 }))(),
  },
});

export const getGetUsersFeedResponseMock = (): UsersFeedResponse => ({
  ...{
    users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        id: faker.string.uuid(),
        firstName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        lastName: faker.string.alpha({ length: { min: 10, max: 100 } }),
        email: faker.internet.email(),
        phone: (() => "09012345678")(),
        postalCode: (() => "100-0001")(),
        prefecture: (() => "神奈川県")(),
        city: (() => "横浜市西区")(),
        street: faker.string.alpha({ length: { min: 10, max: 255 } }),
        building: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 255 } }),
          undefined,
        ]),
        deletedAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          null,
        ]),
      }),
    ),
  },
  ...{
    nextCursor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    hasNext: faker.datatype.boolean(),
  },
});

export const getGetPrefecturesResponseMock = () => [
  { id: "0195f0c2-0000-7000-8000-000000000001", code: 1, name: "北海道" },
  { id: "0195f0c2-0000-7000-8000-000000000004", code: 4, name: "宮城県" },
  { id: "0195f0c2-0000-7000-8000-000000000013", code: 13, name: "東京都" },
  { id: "0195f0c2-0000-7000-8000-000000000014", code: 14, name: "神奈川県" },
  { id: "0195f0c2-0000-7000-8000-000000000023", code: 23, name: "愛知県" },
  { id: "0195f0c2-0000-7000-8000-000000000026", code: 26, name: "京都府" },
  { id: "0195f0c2-0000-7000-8000-000000000027", code: 27, name: "大阪府" },
  { id: "0195f0c2-0000-7000-8000-000000000034", code: 34, name: "広島県" },
  { id: "0195f0c2-0000-7000-8000-000000000038", code: 38, name: "愛媛県" },
  { id: "0195f0c2-0000-7000-8000-000000000040", code: 40, name: "福岡県" },
  { id: "0195f0c2-0000-7000-8000-000000000047", code: 47, name: "沖縄県" },
];

export const getGetProductStatusesResponseMock = () => [
  { id: "0195f0c2-1000-7000-9000-000000000001", code: 1, name: "在庫あり" },
  { id: "0195f0c2-1000-7000-9000-000000000002", code: 2, name: "在庫切れ" },
  { id: "0195f0c2-1000-7000-9000-000000000003", code: 3, name: "予約受付中" },
  { id: "0195f0c2-1000-7000-9000-000000000004", code: 4, name: "販売終了" },
  { id: "0195f0c2-1000-7000-9000-000000000005", code: 5, name: "取り寄せ中" },
  { id: "0195f0c2-1000-7000-9000-000000000006", code: 6, name: "入荷待ち" },
  { id: "0195f0c2-1000-7000-9000-000000000007", code: 7, name: "廃盤" },
  { id: "0195f0c2-1000-7000-9000-000000000008", code: 8, name: "検討中" },
  { id: "0195f0c2-1000-7000-9000-000000000009", code: 9, name: "再入荷予定" },
  { id: "0195f0c2-1000-7000-9000-000000000010", code: 10, name: "限定販売" },
];

export const getGetProductCategoriesResponseMock = () => [
  { id: "0195f0c2-2000-7000-9000-000000000001", code: 1, name: "家電" },
  { id: "0195f0c2-2000-7000-9000-000000000002", code: 2, name: "食品" },
  { id: "0195f0c2-2000-7000-9000-000000000003", code: 3, name: "衣類" },
  { id: "0195f0c2-2000-7000-9000-000000000004", code: 4, name: "書籍" },
  { id: "0195f0c2-2000-7000-9000-000000000005", code: 5, name: "日用品" },
];

export const getGetProductsResponseMock = (): ProductListResponse => ({
  ...{
    products: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        id: faker.string.uuid(),
        name: faker.string.alpha({ length: { min: 10, max: 255 } }),
        description: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        price: (() => "19.99")(),
        quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
        stockWarningThreshold: faker.helpers.arrayElement([
          (() => faker.number.int({ min: 1, max: 20 }))(),
          null,
        ]),
        status: {
          id: faker.string.uuid(),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        },
        category: {
          id: faker.string.uuid(),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        },
        publishedAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          null,
        ]),
        images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
          () => ({
            imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
            displaySort: faker.number.int({ min: 1, max: 32767 }),
          }),
        ),
        version: (() => faker.number.int({ min: 1, max: 20 }))(),
      }),
    ),
  },
  ...{
    nextCursor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    hasNext: faker.datatype.boolean(),
  },
});

export const getPostProductsResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
  stockWarningThreshold: faker.helpers.arrayElement([
    (() => faker.number.int({ min: 1, max: 20 }))(),
    null,
  ]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      displaySort: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: (() => faker.number.int({ min: 1, max: 20 }))(),
  ...overrideResponse,
});

export const getGetProductsCountResponseMock = (
  overrideResponse: Partial<Extract<ProductCountResponse, object>> = {},
): ProductCountResponse => ({
  count: (() => faker.number.int({ min: 0, max: 9999 }))(),
  ...overrideResponse,
});

export const getGetProductsDetailResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
  stockWarningThreshold: faker.helpers.arrayElement([
    (() => faker.number.int({ min: 1, max: 20 }))(),
    null,
  ]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      displaySort: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: (() => faker.number.int({ min: 1, max: 20 }))(),
  ...overrideResponse,
});

export const getPatchProductsDetailResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
  stockWarningThreshold: faker.helpers.arrayElement([
    (() => faker.number.int({ min: 1, max: 20 }))(),
    null,
  ]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      displaySort: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: (() => faker.number.int({ min: 1, max: 20 }))(),
  ...overrideResponse,
});

export const getPatchProductsStockResponseMock = (
  overrideResponse: Partial<Extract<ProductResponse, object>> = {},
): ProductResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 255 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  price: (() => "19.99")(),
  quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
  stockWarningThreshold: faker.helpers.arrayElement([
    (() => faker.number.int({ min: 1, max: 20 }))(),
    null,
  ]),
  status: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  category: { id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  publishedAt: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + "Z",
    null,
  ]),
  images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
      displaySort: faker.number.int({ min: 1, max: 32767 }),
    }),
  ),
  version: (() => faker.number.int({ min: 1, max: 20 }))(),
  ...overrideResponse,
});

export const getGetProductsRankingQuantityResponseMock = (
  overrideResponse: Partial<Extract<ProductQuantityRankingResponse, object>> = {},
): ProductQuantityRankingResponse => ({
  rankings: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      name: faker.string.alpha({ length: { min: 10, max: 255 } }),
      price: (() => "19.99")(),
      soldQuantity: (() => faker.number.int({ min: 0, max: 99 }))(),
    }),
  ),
  ...overrideResponse,
});

export const getGetProductsRankingAmountResponseMock = (
  overrideResponse: Partial<Extract<ProductAmountRankingResponse, object>> = {},
): ProductAmountRankingResponse => ({
  rankings: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      name: faker.string.alpha({ length: { min: 10, max: 255 } }),
      price: (() => "19.99")(),
      salesAmount: (() => "824.69")(),
    }),
  ),
  ...overrideResponse,
});

export const getGetProductsLowStockResponseMock = (
  overrideResponse: Partial<Extract<ProductLowStockResponse, object>> = {},
): ProductLowStockResponse => ({
  products: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      id: faker.string.uuid(),
      name: faker.string.alpha({ length: { min: 10, max: 255 } }),
      description: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      price: (() => "19.99")(),
      quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
      stockWarningThreshold: faker.helpers.arrayElement([
        (() => faker.number.int({ min: 1, max: 20 }))(),
        null,
      ]),
      status: {
        id: faker.string.uuid(),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      category: {
        id: faker.string.uuid(),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      publishedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        null,
      ]),
      images: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
        () => ({
          imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
          displaySort: faker.number.int({ min: 1, max: 32767 }),
        }),
      ),
      version: (() => faker.number.int({ min: 1, max: 20 }))(),
    }),
  ),
  ...overrideResponse,
});

export const getPostProductsImagesResponseMock = (
  overrideResponse: Partial<Extract<ProductImageResponse, object>> = {},
): ProductImageResponse => ({
  imagePath: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetExchangeRatesResponseMock = (
  overrideResponse: Partial<Extract<ExchangeRateResponse, object>> = {},
): ExchangeRateResponse => ({
  base: faker.string.alpha({ length: { min: 10, max: 20 } }),
  quote: faker.string.alpha({ length: { min: 10, max: 20 } }),
  original: (() => "19.99")(),
  converted: (() => "-19.99")(),
  referenceAmount: faker.helpers.arrayElement([
    {
      currency: faker.string.alpha({ length: { min: 10, max: 20 } }),
      amount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
      rate: (() => "19.99")(),
      rateDate: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    null,
  ]),
  ...overrideResponse,
});

export const getGetAddressesResponseMock = (
  overrideResponse: Partial<Extract<AddressCandidatesResponse, object>> = {},
): AddressCandidatesResponse => ({
  candidates: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      prefectureId: faker.helpers.arrayElement([faker.string.uuid(), null]),
      prefectureName: (() => "神奈川県")(),
      city: (() => "横浜市西区")(),
      town: faker.string.alpha({ length: { min: 10, max: 20 } }),
    }),
  ),
  isFallback: faker.datatype.boolean(),
  ...overrideResponse,
});

export const getGetPurchasesResponseMock = (): PurchaseListResponse => ({
  ...{
    items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        code: faker.string.alpha({ length: { min: 10, max: 20 } }),
        totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
        status: {
          id: faker.string.uuid(),
          code: faker.number.int(),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        },
        firstItemName: faker.string.alpha({ length: { min: 10, max: 20 } }),
        itemCount: (() => faker.number.int({ min: 0, max: 9999 }))(),
        orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      }),
    ),
  },
  ...{
    nextCursor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    hasNext: faker.datatype.boolean(),
  },
});

export const getPostPurchasesResponseMock = (
  overrideResponse: Partial<Extract<PurchaseResponse, object>> = {},
): PurchaseResponse => ({
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  statusId: faker.string.uuid(),
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  taxAmount: (() => faker.number.int({ min: 0, max: 99_999 }))(),
  shippingFee: (() => faker.number.int({ min: 0, max: 2000 }))(),
  totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  referenceAmount: faker.helpers.arrayElement([
    {
      currency: faker.string.alpha({ length: { min: 10, max: 20 } }),
      amount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
      rate: (() => "19.99")(),
      rateDate: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    null,
  ]),
  ...overrideResponse,
});

export const getGetPurchaseStatusesResponseMock = () => [
  { id: "0195f0c2-4000-7000-9000-000000000001", code: 1, name: "未処理" },
  { id: "0195f0c2-4000-7000-9000-000000000002", code: 2, name: "受付中" },
  { id: "0195f0c2-4000-7000-9000-000000000003", code: 3, name: "確認中" },
  { id: "0195f0c2-4000-7000-9000-000000000004", code: 4, name: "処理中" },
  { id: "0195f0c2-4000-7000-9000-000000000005", code: 5, name: "完了" },
  { id: "0195f0c2-4000-7000-9000-000000000006", code: 6, name: "キャンセル" },
  { id: "0195f0c2-4000-7000-9000-000000000007", code: 7, name: "支払い済み" },
  { id: "0195f0c2-4000-7000-9000-000000000008", code: 8, name: "発送済み" },
  { id: "0195f0c2-4000-7000-9000-000000000009", code: 9, name: "配達済み" },
];

export const getGetPurchasesShippableResponseMock = (
  overrideResponse: Partial<Extract<PurchaseShippableResponse, object>> = {},
): PurchaseShippableResponse => ({
  groups: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      userId: faker.string.uuid(),
      purchases: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
        () => ({
          code: faker.string.alpha({ length: { min: 10, max: 20 } }),
          totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
          orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        }),
      ),
    }),
  ),
  ...overrideResponse,
});

export const getGetPurchasesDetailResponseMock = (
  overrideResponse: Partial<Extract<PurchaseGetDetailResponse, object>> = {},
): PurchaseGetDetailResponse => ({
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: {
    id: faker.string.uuid(),
    code: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  taxAmount: (() => faker.number.int({ min: 0, max: 99_999 }))(),
  shippingFee: (() => faker.number.int({ min: 0, max: 2000 }))(),
  totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      productName: faker.string.alpha({ length: { min: 10, max: 20 } }),
      quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  paidAt: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
    undefined,
  ]),
  canceledAt: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPatchPurchasesCancelResponseMock = (
  overrideResponse: Partial<Extract<PurchaseCancelResponse, object>> = {},
): PurchaseCancelResponse => ({
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: {
    id: faker.string.uuid(),
    code: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  taxAmount: (() => faker.number.int({ min: 0, max: 99_999 }))(),
  shippingFee: (() => faker.number.int({ min: 0, max: 2000 }))(),
  totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  canceledAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getPatchPurchasesPayResponseMock = (
  overrideResponse: Partial<Extract<PurchasePayResponse, object>> = {},
): PurchasePayResponse => ({
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: {
    id: faker.string.uuid(),
    code: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  taxAmount: (() => faker.number.int({ min: 0, max: 99_999 }))(),
  shippingFee: (() => faker.number.int({ min: 0, max: 2000 }))(),
  totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  paidAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getPatchPurchasesShipResponseMock = (
  overrideResponse: Partial<Extract<PurchaseShipResponse, object>> = {},
): PurchaseShipResponse => ({
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: {
    id: faker.string.uuid(),
    code: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  taxAmount: (() => faker.number.int({ min: 0, max: 99_999 }))(),
  shippingFee: (() => faker.number.int({ min: 0, max: 2000 }))(),
  totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  shippedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getPatchPurchasesDeliverResponseMock = (
  overrideResponse: Partial<Extract<PurchaseDeliverResponse, object>> = {},
): PurchaseDeliverResponse => ({
  code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  userId: faker.string.uuid(),
  status: {
    id: faker.string.uuid(),
    code: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  taxAmount: (() => faker.number.int({ min: 0, max: 99_999 }))(),
  shippingFee: (() => faker.number.int({ min: 0, max: 2000 }))(),
  totalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  details: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      productId: faker.string.uuid(),
      quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
      unitPrice: (() => "19.99")(),
    }),
  ),
  orderedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  deliveredAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getGetDashboardSummaryResponseMock = (
  overrideResponse: Partial<Extract<DashboardSummaryResponse, object>> = {},
): DashboardSummaryResponse => ({
  salesAmount: (() => faker.number.int({ min: 100_000, max: 999_999 }))(),
  salesCount: (() => faker.number.int({ min: 0, max: 9999 }))(),
  purchaseStatusCounts: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    status: {
      id: faker.string.uuid(),
      code: faker.number.int(),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    count: (() => faker.number.int({ min: 0, max: 9999 }))(),
  })),
  totalProductCount: (() => faker.number.int({ min: 0, max: 9999 }))(),
  publishedProductCount: (() => faker.number.int({ min: 0, max: 9999 }))(),
  ...overrideResponse,
});

export const getGetCartsMeResponseMock = (
  overrideResponse: Partial<Extract<CartResponse, object>> = {},
): CartResponse => ({
  sessionToken: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
    undefined,
  ]),
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    productId: faker.string.uuid(),
    productName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
      undefined,
    ]),
    imagePath: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
      undefined,
    ]),
    quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
    unitPrice: faker.helpers.arrayElement([(() => "19.99")(), null]),
    issues: faker.helpers.arrayElements(Object.values(CartItemIssue)),
    availableQuantity: faker.helpers.arrayElement([
      (() => faker.number.int({ min: 0, max: 99 }))(),
      null,
    ]),
  })),
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  expiresAt: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPutCartsMeItemResponseMock = (
  overrideResponse: Partial<Extract<CartResponse, object>> = {},
): CartResponse => ({
  sessionToken: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
    undefined,
  ]),
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    productId: faker.string.uuid(),
    productName: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
      undefined,
    ]),
    imagePath: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
      undefined,
    ]),
    quantity: (() => faker.number.int({ min: 0, max: 99 }))(),
    unitPrice: faker.helpers.arrayElement([(() => "19.99")(), null]),
    issues: faker.helpers.arrayElements(Object.values(CartItemIssue)),
    availableQuantity: faker.helpers.arrayElement([
      (() => faker.number.int({ min: 0, max: 99 }))(),
      null,
    ]),
  })),
  subtotalAmount: (() => faker.number.int({ min: 1000, max: 999_999 }))(),
  expiresAt: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", null]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPostCartsMeMergeResponseMock = (
  overrideResponse: Partial<Extract<CartMergeResponse, object>> = {},
): CartMergeResponse => ({
  clamped: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.uuid(),
  ),
  dropped: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.uuid(),
  ),
  ...overrideResponse,
});

export const getGetStreamMockHandler = (
  overrideResponse?:
    | DeliveryEvent
    | ControlEvent
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<DeliveryEvent | ControlEvent> | DeliveryEvent | ControlEvent),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/streams/:destination",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetStreamResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersMockHandler = (
  overrideResponse?:
    | UsersResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UsersResponse> | UsersResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostUsersMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/users",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostUsersResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetUsersDetailMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPutUsersDetailMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPutUsersDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchUsersDetailMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchUsersDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDeleteUsersDetailMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/v1/users/:userId",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getGetUsersMeMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/me",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersMeResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersMePurchasesSummaryMockHandler = (
  overrideResponse?:
    | PurchaseAggregateResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseAggregateResponse> | PurchaseAggregateResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/me/purchases/summary",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersMePurchasesSummaryResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersMeRolesMockHandler = (
  overrideResponse?:
    | UserRolesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserRolesResponse> | UserRolesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/me/roles",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersMeRolesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersSearchMockHandler = (
  overrideResponse?:
    | UsersSearchResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UsersSearchResponse> | UsersSearchResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/search",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersSearchResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetUsersFeedMockHandler = (
  overrideResponse?:
    | UsersFeedResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UsersFeedResponse> | UsersFeedResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/users/feed",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersFeedResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPrefecturesMockHandler = (
  overrideResponse?:
    | PrefecturesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PrefecturesResponse> | PrefecturesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/prefectures",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPrefecturesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductStatusesMockHandler = (
  overrideResponse?:
    | ProductsStatusesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductsStatusesResponse> | ProductsStatusesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/statuses",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductStatusesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductCategoriesMockHandler = (
  overrideResponse?:
    | ProductsCategoriesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductsCategoriesResponse> | ProductsCategoriesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/categories",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductCategoriesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsMockHandler = (
  overrideResponse?:
    | ProductListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductListResponse> | ProductListResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostProductsMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/products",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostProductsResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetProductsCountMockHandler = (
  overrideResponse?:
    | ProductCountResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductCountResponse> | ProductCountResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/count",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsCountResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsDetailMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/:productId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchProductsDetailMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/products/:productId",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchProductsDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchProductsStockMockHandler = (
  overrideResponse?:
    | ProductResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ProductResponse> | ProductResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/products/:productId/stock",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchProductsStockResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsRankingQuantityMockHandler = (
  overrideResponse?:
    | ProductQuantityRankingResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductQuantityRankingResponse> | ProductQuantityRankingResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/ranking/quantity",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsRankingQuantityResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsRankingAmountMockHandler = (
  overrideResponse?:
    | ProductAmountRankingResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductAmountRankingResponse> | ProductAmountRankingResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/ranking/amount",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsRankingAmountResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetProductsLowStockMockHandler = (
  overrideResponse?:
    | ProductLowStockResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProductLowStockResponse> | ProductLowStockResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/products/low-stock",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetProductsLowStockResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostProductsImagesMockHandler = (
  overrideResponse?:
    | ProductImageResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ProductImageResponse> | ProductImageResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/products/images",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostProductsImagesResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetExchangeRatesMockHandler = (
  overrideResponse?:
    | ExchangeRateResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExchangeRateResponse> | ExchangeRateResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/exchange-rates",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetExchangeRatesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetAddressesMockHandler = (
  overrideResponse?:
    | AddressCandidatesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<AddressCandidatesResponse> | AddressCandidatesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/addresses",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetAddressesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPurchasesMockHandler = (
  overrideResponse?:
    | PurchaseListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseListResponse> | PurchaseListResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/purchases",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPurchasesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostPurchasesMockHandler = (
  overrideResponse?:
    | PurchaseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<PurchaseResponse> | PurchaseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/purchases",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostPurchasesResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetPurchaseStatusesMockHandler = (
  overrideResponse?:
    | PurchasesStatusesResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchasesStatusesResponse> | PurchasesStatusesResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/purchases/statuses",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPurchaseStatusesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPurchasesShippableMockHandler = (
  overrideResponse?:
    | PurchaseShippableResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseShippableResponse> | PurchaseShippableResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/purchases/shippable",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPurchasesShippableResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPurchasesDetailMockHandler = (
  overrideResponse?:
    | PurchaseGetDetailResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchaseGetDetailResponse> | PurchaseGetDetailResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/purchases/:purchaseCode",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPurchasesDetailResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesCancelMockHandler = (
  overrideResponse?:
    | PurchaseCancelResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchaseCancelResponse> | PurchaseCancelResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseCode/cancel",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesCancelResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesPayMockHandler = (
  overrideResponse?:
    | PurchasePayResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchasePayResponse> | PurchasePayResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseCode/pay",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesPayResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesShipMockHandler = (
  overrideResponse?:
    | PurchaseShipResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchaseShipResponse> | PurchaseShipResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseCode/ship",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesShipResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchPurchasesDeliverMockHandler = (
  overrideResponse?:
    | PurchaseDeliverResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<PurchaseDeliverResponse> | PurchaseDeliverResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/v1/purchases/:purchaseCode/deliver",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchPurchasesDeliverResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetDashboardSummaryMockHandler = (
  overrideResponse?:
    | DashboardSummaryResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<DashboardSummaryResponse> | DashboardSummaryResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/dashboard/summary",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetDashboardSummaryResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetCartsMeMockHandler = (
  overrideResponse?:
    | CartResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CartResponse> | CartResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/v1/carts/me",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCartsMeResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDeleteCartsMeMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/v1/carts/me",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getPutCartsMeItemMockHandler = (
  overrideResponse?:
    | CartResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<CartResponse> | CartResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/v1/carts/me/items/:productId",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPutCartsMeItemResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDeleteCartsMeItemMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/v1/carts/me/items/:productId",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getPostCartsMeMergeMockHandler = (
  overrideResponse?:
    | CartMergeResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CartMergeResponse> | CartMergeResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/v1/carts/me/merge",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostCartsMeMergeResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getGoBoilerplateAPIMock = () => [
  getGetStreamMockHandler(),
  getGetUsersMockHandler(),
  getPostUsersMockHandler(),
  getGetUsersDetailMockHandler(),
  getPutUsersDetailMockHandler(),
  getPatchUsersDetailMockHandler(),
  getDeleteUsersDetailMockHandler(),
  getGetUsersMeMockHandler(),
  getGetUsersMePurchasesSummaryMockHandler(),
  getGetUsersMeRolesMockHandler(),
  getGetUsersSearchMockHandler(),
  getGetUsersFeedMockHandler(),
  getGetPrefecturesMockHandler(),
  getGetProductStatusesMockHandler(),
  getGetProductCategoriesMockHandler(),
  getGetProductsMockHandler(),
  getPostProductsMockHandler(),
  getGetProductsCountMockHandler(),
  getGetProductsDetailMockHandler(),
  getPatchProductsDetailMockHandler(),
  getPatchProductsStockMockHandler(),
  getGetProductsRankingQuantityMockHandler(),
  getGetProductsRankingAmountMockHandler(),
  getGetProductsLowStockMockHandler(),
  getPostProductsImagesMockHandler(),
  getGetExchangeRatesMockHandler(),
  getGetAddressesMockHandler(),
  getGetPurchasesMockHandler(),
  getPostPurchasesMockHandler(),
  getGetPurchaseStatusesMockHandler(),
  getGetPurchasesShippableMockHandler(),
  getGetPurchasesDetailMockHandler(),
  getPatchPurchasesCancelMockHandler(),
  getPatchPurchasesPayMockHandler(),
  getPatchPurchasesShipMockHandler(),
  getPatchPurchasesDeliverMockHandler(),
  getGetDashboardSummaryMockHandler(),
  getGetCartsMeMockHandler(),
  getDeleteCartsMeMockHandler(),
  getPutCartsMeItemMockHandler(),
  getDeleteCartsMeItemMockHandler(),
  getPostCartsMeMergeMockHandler(),
];
